const {chromium}=require('playwright');require('fs').mkdirSync('shots-modes',{recursive:true});
(async()=>{const b=await chromium.launch({executablePath:(process.env.CHROME||'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'),args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const ctx=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const p=await ctx.newPage();const errs=[];
p.on('pageerror',e=>errs.push(e.message));await p.route(/googletagmanager|google-analytics|facebook|clarity|formspree|fonts\.g/,r=>r.abort());
const shot=async(n,w)=>{await p.waitForTimeout(w||2600);await p.evaluate(()=>window.__tq.api.settle());await p.waitForTimeout(700);await (await p.$('#stage')).screenshot({path:'shots-modes/'+n+'.png'});const m=await p.$eval('#ovMsg',e=>e.hidden?'':e.innerText.replace(/\n/g,' ')).catch(()=>'');console.log(n,'|',m.slice(0,150));};
await p.goto('http://localhost:8765/window-cleaning-hesperia.html');await p.waitForFunction(()=>window.__tq&&window.__tq.api,null,{timeout:90000});await p.waitForTimeout(2500);
await p.screenshot({path:'shots-modes/hero-window-page.png'});
await p.click('.tq-intro [data-mode="tour"]');await shot('01-welcome');
await p.click('.obd [data-o="hood"] [data-v="1"]');await p.click('.obd [data-obd="next"]');await shot('02-problems',800);
await p.click('.obd input[value="sol"]');await p.click('.obd input[value="pig"]');await p.waitForTimeout(200);
console.log('count rows after checking solar and pigeons',await p.$$eval('.obd [data-det]',l=>l.filter(x=>!x.hidden).map(x=>x.getAttribute('data-det')).join(',')));
await p.click('.obd [data-step="panels"] [data-d="-1"]');console.log('panel count set in the welcome',await p.evaluate(()=>window.__tq.st.panels));
await p.click('.obd [data-obd="build"]');await shot('03-tour-over',3500);
console.log('Tony introduces himself',/Hi, I'm Tony/.test(await p.$eval('#ovMsg',e=>e.innerText)));
const hs=await p.$$eval('.hs',l=>l.filter(x=>!x.hidden).map(x=>x.textContent));console.log('labels',hs.join(','));
for(let i=4;i<=8;i++){await p.click('#ovNav .nx');await shot('0'+i+'-tour',3200);}
console.log('panel folded after the welcome',await p.$eval('#ov',e=>e.classList.contains('min')));
await p.click('.ov-tabs [data-hmode="pig"]');await p.waitForTimeout(1500);
await p.click('#ovGrab');await p.waitForTimeout(300);console.log('grab label',await p.$eval('#ovGrab span',e=>e.textContent));
console.log('pigeon chips',await p.$$eval('#try button',l=>l.map(x=>x.textContent).join(',')));
await p.click('#try [data-try="clips"]');await shot('09-clips',2200);
await p.click('[data-hseg="stage"] [data-v="3"]');await shot('10-reach',4500);
await p.click('#ovNav .nx');await shot('11-nextdoor',5500);
await p.click('.ov-tabs [data-hmode="home"]');await p.waitForTimeout(800);await p.click('[data-otab="street"]');await p.click('[data-hseg="hood"] [data-v="2"]');await shot('12-acreage',4000);
await p.click('[data-hseg="hood"] [data-v="0"]');await shot('13-desert',3500);
await p.click('[data-otab="home"]');await p.click('[data-hseg="style"] [data-v="4"]');await p.click('[data-otab="street"]');await p.click('[data-hseg="hood"] [data-v="4"]');await shot('13b-mountain',4000);
console.log('mountain cabin built',JSON.stringify(await p.evaluate(()=>{const s=window.__tq.api.state();return [s.style,s.h3.hood];})));
/* the added models: a manufactured home on acreage (one story, shingle roof) and an older desert home, then back to the cabin */
await p.click('[data-otab="home"]');await p.click('[data-hseg="style"] [data-v="6"]');await p.click('[data-otab="street"]');await p.click('[data-hseg="hood"] [data-v="2"]');await shot('13c-manufactured',4000);
console.log('manufactured home on acreage, one story, shingle',JSON.stringify(await p.evaluate(()=>{const s=window.__tq.api.state();return [s.style,s.h3.hood,window.__tq.st.stories,s.h3.roof];})));
await p.click('[data-otab="home"]');await p.click('[data-hseg="style"] [data-v="5"]');await shot('13d-older',3500);
console.log('older desert home built',JSON.stringify(await p.evaluate(()=>{const s=window.__tq.api.state();return [s.style,window.__tq.st.stories];})));
await p.click('[data-hseg="style"] [data-v="4"]');await p.click('[data-otab="street"]');await p.click('[data-hseg="hood"] [data-v="4"]');await p.waitForTimeout(1500);
await p.click('#askb');await p.waitForTimeout(300);console.log('ask Tony chips',await p.$$eval('#askp button',l=>l.length));await p.click('#askp button');await p.waitForTimeout(300);console.log('answer shown',/Do I need to be home/.test(await p.$eval('#ovMsg',e=>e.innerText)));await p.click('#askp .back');
await p.evaluate(()=>{const s=window.__tq.st;s.pig=false;s.spin=0;s.sol=true;window.__tq.render();});
await p.click('.ov-tabs [data-hmode="sol"]');await p.evaluate(()=>window.__tq.api.seek(4));await shot('14-solar',2500);
console.log('solar chips',await p.$$eval('#try button',l=>l.map(x=>x.textContent).join(' / ')));
console.log('no sales chips while the wash runs',await p.$$eval('#try button',l=>l.length)===0);
await p.click('#ovNav .nx');await p.waitForTimeout(900);console.log('solar chips when done',await p.$$eval('#try button',l=>l.map(x=>x.textContent).join(' / ')));
await p.click('#try [data-try="see:pig"]');await p.waitForTimeout(1500);console.log('pigeon view from the solar suggestion, not added to the quote',await p.evaluate(()=>[window.__tq.api.state().mode,window.__tq.st.pig].join(' ')));
await p.evaluate(()=>{const s=window.__tq.st;s.spin=2;window.__tq.render();});console.log('spinners only on the ticket',/2 reflective spinners on the roof vents/.test(await p.$eval('#tlines',e=>e.innerText)),await p.$eval('#ttotal',e=>e.textContent));
await p.click('.ov-tabs [data-hmode="win"]');await p.waitForTimeout(1500);await p.evaluate(()=>{const S=window.__tq.api.state().steps;window.__tq.api.seek(S[S.length-1]+.5);});await p.waitForTimeout(900);await p.click('#try [data-try="inside"]');await p.waitForTimeout(1500);console.log('inside added from the picture',await p.evaluate(()=>window.__tq.st.inside),await p.$eval('#ovMsg',e=>e.innerText.slice(0,90)));
console.log(errs.join(' | ')||'no errors');await b.close();})();
