# Page specs, English. Each page is written by hand for the question it answers. No city name swaps.
# Prices come from the same numbers the quote tool uses. Nothing here names a customer or a job we did not do.
S = 'https://twindowclean.com/'
OG = lambda n: S + 'assets/og/' + n + '.jpg'

PAGES = []

PAGES.append({
    'fn': 'screen-replacement.html',
    'title': 'Window Screen Replacement in the High Desert | Tony\'s',
    'desc': 'New window screens built to fit on site, frame and mesh, from $63.99 a screen in Hesperia, Victorville and Apple Valley. Same visit, 2 year warranty.',
    'og_image': OG('screen-repair'), 'crumb': 'Screen Replacement', 'parent': ('Screen Repair', S + 'screen-repair.html'),
    'where': 'Serving Hesperia and the High Desert',
    'h1': 'Window Screen <span class="grad">Replacement</span>', 'tagline': 'A whole new screen, frame and mesh, built on site from $63.99. Same visit, 2 year warranty on the mesh.',
    'lede': 'When the frame is bent, the corners are gone or the screen has been missing since the last windstorm, re-meshing is not enough. We build a new one to your window\'s exact size at the truck, set the spline, and it snaps in before we leave.',
    'schema_name': 'Window Screen Replacement', 'service_type': 'Window screen replacement', 'price': '63.99',
    'price_desc': 'New window screen built on site: frame, corners, clips and charcoal fiberglass mesh. All weather mesh $74.99.',
    'sections': [
        ('text', 'Replace or re-mesh', 'Which one your screen needs',
         ['Re-meshing keeps your frame and gives it new mesh. It costs $53.99 in charcoal fiberglass or $64.99 in all weather, and it is the right call when the frame is straight and the corners still hold. Most screens we see qualify.',
          'Replacement is for the rest: frames that came off in the wind and got stepped on, corners that crumbled, screens that were never there when you bought the house. New frame and corners are $10 on top of the mesh, so a new charcoal fiberglass screen is $63.99 and a new all weather screen is $74.99.',
          'We decide screen by screen at your window, not from the driveway. A house with 14 screens might need 11 re-meshed and 3 rebuilt, and that is exactly how it goes on the quote.']),
        ('tiles', 'What you get', 'Built at the truck, fitted at the window',
         [('Measured twice', 'Every opening is measured, because tract homes in Victorville and Hesperia use three or four sizes on one wall and the old screen is not always the right one.'),
          ('Frame, corners, clips', 'New aluminum frame stock cut and cornered on site, with the clips or springs your window takes. It goes in the way the builder\'s did, no forcing.'),
          ('Your choice of mesh', 'Charcoal fiberglass for the clearest view, or all weather mesh for windows that face the afternoon sun, get wind, or have dogs and cats behind them.')]),
        ('text', 'Why they fail here', 'What High Desert screens go through',
         ['Builder mesh is fine at sea level. Up here it gets nine months of hard UV, then wind that runs 30 to 50 miles an hour a few times each season. The mesh goes brittle first, then a gust bows it out of the spline and the frame twists. Once a frame twists it never sits right again.',
          'That is why we push all weather mesh on south and west windows even when we are only re-meshing. It is heavy vinyl coated polyester, several times stronger than fiberglass, and it takes the sun without going chalky.']),
        ('text', 'Price', 'What screen replacement costs',
         ['$63.99 a screen in charcoal fiberglass, $74.99 in all weather, frame and mesh included. Re-mesh only is $53.99 or $64.99. If screens are the only service on the visit there is a $149 minimum, which is three screens.',
          'Screens are usually added to a window cleaning, and then there is no minimum. Book on our website and the first visit takes 10% off. Use the tool above, set your screen count, and the total is your price.']),
        ('photos', 'Our work', 'Screens we have rebuilt and re-meshed', 'Our own photos from real jobs across the High Desert.',
         [('assets/photos/hub-screen-repair-01.jpg', 'New window screen being fitted on a High Desert home'),
          ('assets/photos/hub-screen-repair-02.jpg', 'Re-meshed window screens ready to go back in'),
          ('assets/photos/spring-valley-lake-screen-01.jpg', 'Replaced window screen on a Spring Valley Lake home'),
          ('assets/photos/hub-screen-repair-03.jpg', 'All weather mesh on a rebuilt screen frame')]),
        ('cta', 'New screens <span class="grad">this week</span>', 'Set your screen count above and the price is your price.', 'Get my price'),
    ],
    'faq_title': 'Screen replacement questions',
    'faq': [
        ('Do I need a whole new screen or just new mesh?', 'If the frame is straight and the corners hold, new mesh is enough and it is $10 cheaper. If the frame is bent, missing corners or missing altogether, we build a new one. We check each screen at the window and the quote says which is which.'),
        ('How much is a new window screen?', '$63.99 in charcoal fiberglass or $74.99 in all weather mesh, frame, corners and clips included. Re-mesh only is $53.99 or $64.99. Three screen minimum when screens are the only service that day.'),
        ('Can you match my existing screens?', 'Frames come in the standard finishes and the mesh is charcoal, the same as most builder screens, so a rebuilt screen sits next to an original without standing out. If your home has bronze frames we match those too.'),
        ('Do you do this at my house or take them away?', 'At your house, the same visit. We carry frame stock, corners, spline and both meshes on the truck, so nothing leaves and nothing comes back a week later.'),
        ('What is the warranty?', 'Two years on the mesh and the work. If a screen we built sags, tears at the spline or pops a corner in that time, we fix it.'),
    ],
})

PAGES.append({
    'fn': 'all-weather-mesh.html',
    'title': 'All Weather Screen Mesh for High Desert Sun | Tony\'s',
    'desc': 'All weather screen mesh, the heavy vinyl coated polyester that takes High Desert sun, wind and pets. $64.99 a screen re-meshed on site, 2 year warranty.',
    'og_image': OG('screen-repair'), 'crumb': 'All Weather Mesh', 'parent': ('Screen Repair', S + 'screen-repair.html'),
    'where': 'Serving Hesperia and the High Desert',
    'h1': 'All Weather <span class="grad">Screen Mesh</span>', 'tagline': 'The mesh we recommend on every sun facing window up here. $64.99 a screen, re-meshed on site.',
    'lede': 'Standard window screen is fiberglass thread with a thin coating. All weather mesh is a polyester core inside a thick vinyl jacket. On a shaded window the difference does not matter much. On a west window in Apple Valley in August, it is the difference between a screen that lasts and one that crumbles in your hand.',
    'schema_name': 'All Weather Screen Mesh Re-meshing', 'service_type': 'Window screen re-meshing', 'price': '64.99',
    'price_desc': 'Screen re-meshed on site with all weather vinyl coated polyester mesh.',
    'sections': [
        ('tiles', 'The material', 'What makes it all weather',
         [('Polyester core, vinyl jacket', 'Each strand is polyester wrapped in PVC. The jacket takes the UV so the core never does, which is why it stays flexible for years instead of turning chalky.'),
          ('About five times the strength', 'It resists tearing at the spline where fiberglass lets go, and a dog pushing on it flexes and comes back instead of ripping.'),
          ('Slightly heavier weave', 'You give up a little airflow and a little clarity against charcoal fiberglass. On a shaded north window we will tell you to keep fiberglass and save the $11.')]),
        ('text', 'Where it belongs', 'Which windows should get it',
         ['South and west facing windows in Hesperia, Victorville, Apple Valley and Adelanto, without question. Those take the full afternoon sun nine months a year and every builder screen we pull from them is brittle.',
          'Any window a dog or cat sits behind. Sliding door screens and low bedroom windows are the usual ones. Pet claws go straight through fiberglass; they slide off vinyl coated polyester.',
          'Homes on the open desert in Phelan, Oak Hills and the Mesa, where wind carries grit that sandblasts a screen over a season. The heavier strand shrugs it off.']),
        ('text', 'Honest trade offs', 'What all weather mesh is not',
         ['It is not invisible. Charcoal fiberglass is the clearest mesh made, and if a picture window with a view is your priority, that is the one to keep. We re-mesh plenty of homes with fiberglass on the view side and all weather everywhere else.',
          'It is not pet proof in the sense of stopping a large dog that wants out. It stops claws and noses. A determined 80 pound dog will still bend a frame.']),
        ('text', 'Price', 'What it costs',
         ['$64.99 a screen re-meshed on site with all weather mesh, against $53.99 for charcoal fiberglass. New frames and corners are $10 more when the old frame is bent. Three screen minimum when screens are the only service that day, no minimum when we are already there for windows.',
          'Set your screen count in the tool above and switch the mesh to All weather. The price updates and the 3D shows the two meshes side by side.']),
        ('cta', 'Screens that <span class="grad">outlast the sun</span>', 'Pick All weather in the tool above and see the price on your screen count.', 'Get my price'),
    ],
    'faq_title': 'All weather mesh questions',
    'faq': [
        ('Is all weather mesh the same as pet screen?', 'Same family of material, sold under a few names: pet screen, pet resistant, heavy duty, all weather. Vinyl coated polyester is what matters. Ours is the heavy grade, not the thin version some hardware stores carry.'),
        ('Can I see through it as well as regular screen?', 'Almost. The strands are a little thicker so the view is a touch darker, most people stop noticing within a day. On a window where the view is the whole point, keep charcoal fiberglass there and put all weather on the sun side.'),
        ('How long does it last up here?', 'Fiberglass builder screens usually give out in three to six summers of High Desert sun. All weather mesh on the same window is still flexible well past that. We put a 2 year warranty on the mesh and the work.'),
        ('Do you carry it on the truck?', 'Yes, both meshes, spline in the common sizes, frame stock and corners. Screens are done at your house the same visit, nothing goes to a shop.'),
        ('Is it worth the extra $11 a screen?', 'On a sun facing window or a pet window, yes, because it avoids doing the job again in three years. On a shaded window, no, and we will say so at the window.'),
    ],
})

PAGES.append({
    'fn': 'sliding-door-screen-repair.html',
    'title': 'Sliding Screen Door Repair, High Desert | Tony\'s',
    'desc': 'Sliding patio screen doors re-meshed on site in Hesperia, Victorville and Apple Valley. Rollers checked, track cleaned, priced at the door before we start.',
    'og_image': OG('screen-repair'), 'crumb': 'Sliding Screen Doors', 'parent': ('Screen Repair', S + 'screen-repair.html'),
    'where': 'Serving Hesperia and the High Desert',
    'h1': 'Sliding Screen <span class="grad">Door Repair</span>', 'tagline': 'Patio screen doors re-meshed on site, rollers and track sorted the same visit. Priced at the door, never a surprise.',
    'lede': 'The patio screen door takes more abuse than every window screen in the house put together. Kids run through it, dogs lean on it, the wind slams it, and the bottom rollers fill with grit until it jumps the track. Most of them can be brought back in under an hour without buying a new door.',
    'schema_name': 'Sliding Screen Door Repair', 'service_type': 'Sliding screen door repair', 'price': None,
    'sections': [
        ('text', 'What we do', 'The usual fix, start to finish',
         ['We lift the door out, strip the old mesh and spline, and re-mesh it flat on a table so the tension is even. Doors get all weather mesh unless you ask otherwise, because a door is where fiberglass fails first.',
          'While it is out we check the rollers. Grit and dog hair pack into the wheels, they stop turning and start dragging, and the door bounces off the track. Cleaning and adjusting them is part of the job. If a wheel is cracked or the axle is gone we tell you before we do anything.',
          'The track gets vacuumed and wiped. Then the door goes back in, gets set so it latches without lifting, and we slide it a dozen times before we call it done.']),
        ('tiles', 'What usually goes wrong', 'Three doors we see every week',
         [('Bowed mesh, frame fine', 'The most common one. New all weather mesh and it is a new door. Same visit.'),
          ('Jumps the track', 'Rollers packed with grit or a track that is bent from being forced. Cleaned, adjusted, and we straighten a mild bend. A crushed track is a new door and we say so.'),
          ('Frame kinked in the corner', 'A door that got caught in the wind. Sometimes the corner can be reset, sometimes it cannot. We look before we quote.')]),
        ('text', 'Price', 'How sliding doors are priced',
         ['Doors vary too much for one number: standard height, tall, double wide, doors with kick plates, doors with rollers you can still buy and doors with rollers you cannot. We price it at the door, before we start, and it does not move once we begin.',
          'Add it to a window cleaning or a screen visit and there is no minimum. On its own, the $149 screen minimum applies. Book on our website and take 10% off the visit.']),
        ('photos', 'Our work', 'Screens done on site', 'Our own photos, real jobs across the High Desert.',
         [('assets/photos/hub-screen-repair-02.jpg', 'Re-meshed screens laid out at the truck before going back in'),
          ('assets/photos/hub-screen-repair-01.jpg', 'Screen being fitted on a High Desert home'),
          ('assets/photos/hub-screen-repair-03.jpg', 'All weather mesh tensioned in a frame')]),
        ('cta', 'A patio door that <span class="grad">slides again</span>', 'Add it to your quote above or text us a photo of the door.', 'Get my price'),
    ],
    'faq_title': 'Sliding screen door questions',
    'faq': [
        ('Can you fix the door or do I need a new one?', 'Most of the time we can fix it. Torn or bowed mesh, dirty or sticking rollers and a mildly bent track are all repairs. A crushed track, a frame kinked in two corners or rollers nobody makes anymore usually mean a new door, and we tell you that at the door before any work.'),
        ('What mesh goes on a patio door?', 'All weather mesh unless you ask for fiberglass. A door gets pushed, leaned on and slammed, and vinyl coated polyester takes that where fiberglass tears at the spline within a year.'),
        ('Do you fix the rollers?', 'Cleaning and adjusting the rollers is part of every door we re-mesh. If a roller is broken we can replace it when a matching part exists, and we let you know if it does not.'),
        ('How much does it cost?', 'It depends on the door and what it needs, so we price it in front of you before we start. Add it to a window cleaning and there is no minimum. On its own, the $149 screen minimum applies.'),
        ('Do you do this the same day as the windows?', 'Yes. Doors and window screens are done at your house during the same visit as the window cleaning, and the door goes back in before we leave.'),
    ],
})

PAGES.append({
    'fn': 'solar-panel-cleaning-warranty-safe.html',
    'title': 'Warranty Safe Solar Panel Cleaning | Tony\'s Window Cleaning',
    'desc': 'Solar panel cleaning that keeps your warranty intact: purified water, a soft brush, nobody walks on the panels, no soap, no pressure. $7 a panel.',
    'og_image': OG('solar-panel-cleaning'), 'crumb': 'Warranty Safe Cleaning', 'parent': ('Solar Panel Cleaning', S + 'solar-panel-cleaning.html'),
    'where': 'Serving Hesperia and the High Desert',
    'h1': 'Solar Cleaning That Keeps Your <span class="grad">Warranty</span>', 'tagline': 'Purified water, a soft brush, and feet that never touch a panel. $7 a panel.',
    'lede': 'Every panel maker publishes cleaning rules, and they all say the same three things: no abrasives, no harsh chemicals, no pressure washers. Most of them also say not to walk on the modules. Our method is built around those rules, which is why the warranty question has a short answer.',
    'schema_name': 'Warranty Safe Solar Panel Cleaning', 'service_type': 'Solar panel cleaning', 'price': '7.00',
    'price_desc': 'Solar panel cleaning with purified water and a soft brush, $7 a panel, dried spot free.',
    'sections': [
        ('tiles', 'The method', 'What touches your panels and what does not',
         [('Purified water only', 'Deionized water carries no minerals, so it dries with nothing left behind. No soap, no rinse aid, no chemicals that could react with the anti reflective coating.'),
          ('Soft brush on a pole', 'A soft bristle brush on a water fed pole, worked from the roof edge or the ground. No scrapers, no scouring pads, no pressure washer.'),
          ('Nobody on the modules', 'We work from the roof deck beside the array, not on it. Standing on a panel can microcrack cells that still look fine from the ground.')]),
        ('text', 'What the rules say', 'What installers and panel makers ask for',
         ['The maintenance sections of the big manufacturers\' manuals read almost alike: clean with water and a soft cloth or brush, no abrasive materials, no high pressure, avoid cleaning a hot panel with cold water. Some installers add their own line about not walking on the array. We follow all of it, and we clean early in the morning when panels are cool for the same reason the manuals give.',
          'What voids warranties in practice is damage: cracked glass from a boot, scratched coating from a scrub pad, a corroded connector from a pressure washer forcing water into a junction box. None of those happen with a soft brush and purified water.']),
        ('text', 'What you get', 'The visit, and what we look for while we are up there',
         ['Every panel washed row by row and left to dry spot free. Nothing to wipe, because purified water leaves no minerals. We look over the whole array while we are there: loose wiring, lifted flashing, cracked glass, and birds under the panels, which is the single most common problem we find.',
          'If we find something, you get a photo and a plain explanation. If it is birds, pigeon proofing includes the panel wash free, so nothing you paid today is wasted.']),
        ('text', 'Price', 'What it costs',
         ['$7 a panel, any roof pitch, any panel size. A 20 panel array is $140. Panels are counted from the street or from your solar app, close is fine, and we confirm on site. Book on our website and the first visit is 10% off.',
          'Every 3 months on a plan is 25% off each visit after the first, which is what we suggest for arrays near open desert or sprinklers.']),
        ('photos', 'Our work', 'Arrays we have cleaned', 'Our own photos from High Desert roofs.',
         [('assets/photos/hub-solar-02.jpg', 'Solar array being washed with a water fed pole'),
          ('assets/photos/hesperia-solar-01.jpg', 'Clean solar panels on a Hesperia home'),
          ('assets/photos/oak-hills-solar-03.jpg', 'Solar array in Oak Hills after cleaning'),
          ('assets/photos/apple-valley-solar-02.jpg', 'Two story Apple Valley home with clean panels')]),
        ('cta', 'Clean panels, <span class="grad">warranty intact</span>', 'Set your panel count above and watch the wash in 3D.', 'Get my price'),
    ],
    'faq_title': 'Warranty and cleaning questions',
    'faq': [
        ('Will cleaning my solar panels void the warranty?', 'Not the way we do it. Manufacturers ask for water, a soft brush, no abrasives, no chemicals and no pressure washing, and that is our whole method. What voids warranties is damage, and a soft brush with purified water does not cause any.'),
        ('Do you walk on the panels?', 'No. We work from the roof deck beside the array with a water fed pole. Stepping on a module can microcrack cells that still look perfect from the ground.'),
        ('Why purified water instead of tap water?', 'Tap water up here is hard. It dries into white mineral spots that block light, which is the problem you were trying to fix. Deionized water has nothing in it, so the panel dries clear with nothing to wipe.'),
        ('Do you use soap or any cleaner?', 'No. Soap leaves a film and some cleaners react with anti reflective coatings. Purified water and agitation from the brush lift desert dust and bird droppings without anything else.'),
        ('Can you tell if there is damage while cleaning?', 'Yes, and we look for it on every visit: cracked glass, loose wiring, lifted flashing and birds nesting under the array. You get a photo and a straight answer, not a sales pitch.'),
    ],
})

PAGES.append({
    'fn': 'solar-cleaning-maintenance-plan.html',
    'title': 'How Often to Clean Solar Panels in the High Desert | Tony\'s',
    'desc': 'How often solar panels need cleaning in the High Desert, and what a 3 month plan costs: $7 a panel, 25% off every visit after the first, checks included.',
    'og_image': OG('solar-panel-cleaning'), 'crumb': 'Solar Cleaning Plan', 'parent': ('Solar Panel Cleaning', S + 'solar-panel-cleaning.html'),
    'where': 'Serving Hesperia and the High Desert',
    'h1': 'How Often to Clean <span class="grad">Solar Panels</span> Up Here', 'tagline': 'Every 3 months for most High Desert roofs. On a plan that is 25% off each visit after the first, and we text you before every one.',
    'lede': 'Down the hill, rain rinses panels a few times a winter. Up here we get a handful of storms a year and wind most weeks, so dust builds until someone washes it off. The question is not whether to clean, it is how often, and the honest answer depends on your street.',
    'schema_name': 'Solar Panel Cleaning Maintenance Plan', 'service_type': 'Solar panel cleaning', 'price': '7.00',
    'price_desc': 'Solar panel cleaning every 3 months at $7 a panel, 25% off each visit after the first.',
    'sections': [
        ('tiles', 'How often', 'A schedule by where you live',
         [('Every 3 months', 'Open desert edges of Hesperia, Adelanto, Phelan and Oak Hills, anything next to a dirt road, and any array near sprinklers. Dust and overspray both bake on in a summer.'),
          ('Twice a year', 'Established tracts in Victorville, Apple Valley and Spring Valley Lake with paved streets and lawns. Spring after the wind season, fall after the summer heat.'),
          ('Once a year, at least', 'Shaded or sheltered arrays. Even these lose output by the end of a dry year, and once a year is when we catch birds before they have raised a second brood.')]),
        ('text', 'What dust costs', 'Why the schedule matters',
         ['Open your solar app and compare a sunny day this week with the same day a month after the last wash. That gap is what dust is taking, every day, and it grows through the dry months. Droppings are worse than dust: one bird\'s worth on one cell can pull a whole panel down.',
          'The 3 month visit is also when things get caught early. Panels are checked for cracks, wiring for sagging, and the array edge for birds. If you have pigeon mesh, the clips and mesh get looked over and the spinners get a spin. Nothing on a roof fixes itself.']),
        ('text', 'The plan', 'What a plan is and what it is not',
         ['A plan is a schedule, not a contract. Every 3 months is 25% off each visit after the first, twice a year is 15% off, once a year is the regular price with a reminder. Tony texts you before every visit, you can skip one, and there is nothing to cancel.',
          'At $7 a panel, a 20 panel array is $140 on the first visit and $105 on each plan visit after that. Four visits a year run about $455 instead of $560 booked one at a time. Set your count in the tool above and pick Every 3 months to see your own numbers.']),
        ('text', 'With pigeon proofing', 'If you have mesh or want it',
         ['Pigeon proofing includes the panel wash free on the day, and a year of cleanings can be added: three more washes, every 3 months, at $7 a panel. Each one doubles as a spinner, clip and mesh check, which is exactly when a loose clip gets caught before a bird does.']),
        ('cta', 'Panels that <span class="grad">stay at full output</span>', 'Set your panel count and pick a plan above. Tony texts before every visit.', 'Get my price'),
    ],
    'faq_title': 'Solar cleaning schedule questions',
    'faq': [
        ('How often should solar panels be cleaned in the High Desert?', 'Every 3 months for arrays near open desert, dirt roads or sprinklers, twice a year for established tracts with paved streets, and at least once a year for anything sheltered. There is not enough rain up here to count on it.'),
        ('Does rain clean solar panels?', 'A hard rain rinses loose dust, but it does not move baked on film or droppings, and it leaves its own mineral spots as it dries. Up here we get so few storms that rain is not a cleaning plan.'),
        ('How much output does dust really cost?', 'It depends on the season and the street. Your solar app will show it: compare a clear day right after a wash with one a couple of months later. The gap is real money over a year, and droppings on a single cell cost more than dust on the whole panel.'),
        ('What does a plan cost?', '$7 a panel on the first visit. Every 3 months is 25% off each visit after that, twice a year is 15% off, once a year is the regular price. No contract, and Tony texts before every visit.'),
        ('Can I skip a visit?', 'Yes. The plan is a reminder and a discount, not a commitment. Reply to the text and we move it.'),
    ],
})

PAGES.append({
    'fn': 'solar-panel-bird-mesh-cost.html',
    'title': 'How Much Does Pigeon Proofing Solar Panels Cost? | Tony\'s',
    'desc': 'Pigeon proofing solar panels costs $450 for up to 12 panels and $50 a panel after that, with cleanout, mesh, spinners and a panel wash. The math worked out.',
    'og_image': OG('pigeon-proofing'), 'crumb': 'Pigeon Proofing Cost', 'parent': ('Pigeon Proofing', S + 'pigeon-proofing.html'),
    'where': 'Serving Hesperia and the High Desert',
    'h1': 'What Pigeon Proofing <span class="grad">Solar Panels</span> Costs', 'tagline': '$450 covers up to 12 panels. $50 a panel after that. Everything else is included, and here is the math.',
    'lede': 'Pigeon proofing quotes range from a few hundred dollars to well over a thousand, and the difference is usually what is left out. Ours includes the cleanout, the sanitizing, the mesh, the spinners, a panel wash and a roof wash. Below is what that adds up to for real array sizes.',
    'schema_name': 'Solar Panel Pigeon Proofing Cost', 'service_type': 'Solar panel pigeon proofing', 'price': '450.00',
    'price_desc': 'Pigeon proofing up to 12 panels: cleanout, sanitizing, rigid mesh clipped to the frame, 2 to 3 spinners, panel wash and roof wash.',
    'sections': [
        ('tiles', 'The math', 'Three common arrays, priced',
         [('12 panels: $450', 'The base price covers the whole job on a typical single story array. Cleanout, mesh, 2 spinners, panel wash and roof wash, all in.'),
          ('20 panels: $850', '$450 plus 8 panels over 12 at $50 each. The larger arrays in Hesperia\'s Ranchero tracts and Apple Valley land here, with 3 spinners free.'),
          ('30 panels: $1,350', '$450 plus 18 panels at $50. Two story homes with two roof planes usually need an extra spinner or two at $50 each so both sides are covered.')]),
        ('text', 'What is inside the price', 'Why the base price is $450',
         ['The cleanout is the biggest part of the labor. Nests, droppings and debris come out from under every panel and get hauled off, and the area is sanitized so the smell goes with it. A roof with a year of nesting can take half a day before any mesh goes on.',
          'The mesh is rigid, rust resistant steel, cut to the array and held by clips that grip the lip of the panel frame. Nothing is drilled or screwed, so your panel warranty stays intact. Then the panels get washed with purified water and the roof gets a soft wash, which on their own would be $7 a panel and from $599.',
          'Two to three reflective spinners go on the roof vents free, depending on the size of the roof. Extra spinners are $50 each, and the 3D above shows exactly what one covers and why a ridge needs two.']),
        ('text', 'What moves the price', 'The three things that change a quote',
         ['Panel count is the main one, at $50 a panel past 12. Roof shape is the second: an array split across the front and back of a two story usually wants an extra spinner so both sides get the flash. The third is how long the birds have been there, which changes the cleanout time but not the price. We quote the number and stick to it.',
          'What does not change it: tile versus shingle, one story versus two, or how many birds are on the roof today.']),
        ('text', 'Compared with waiting', 'What a year of not doing it costs',
         ['Droppings are acidic. A year on concrete tile leaves staining that does not fully come back, a year on the panels blocks whole cells and the output loss shows in your solar app. Pigeons raise more than one brood a season, so the flock on your roof next spring is bigger than the one there now, and the cleanout with it.',
          'A 2 year pigeon free warranty comes in writing with every job. Book on our website and the day is 10% off.']),
        ('photos', 'Our work', 'Arrays we have closed off', 'Our own photos from High Desert roofs.',
         [('assets/photos/hub-pigeon-proofing-01.jpg', 'Rigid mesh clipped along the edge of a solar array'),
          ('assets/photos/hesperia-pigeon-03.jpg', 'Pigeon proofed solar array in Hesperia'),
          ('assets/photos/apple-valley-pigeon-01.jpg', 'Pigeon mesh on a two story Apple Valley home'),
          ('assets/photos/oak-hills-pigeon-05.jpg', 'Sealed array on an Oak Hills roof')]),
        ('cta', 'Your number in <span class="grad">one tap</span>', 'Set your panel count above. The price you see is the price.', 'Get my price'),
    ],
    'faq_title': 'Pigeon proofing cost questions',
    'faq': [
        ('How much does pigeon proofing cost for solar panels?', '$450 for up to 12 panels, then $50 for each panel over 12. That includes the cleanout, sanitizing, rigid mesh clipped to the frame, 2 to 3 spinners, a panel wash and a roof wash. A 20 panel array is $850, a 30 panel array is $1,350.'),
        ('Why do some quotes come in lower?', 'Usually the cleanout or the roof wash is missing, the mesh is plastic or chicken wire, or it is screwed into the frame. Ask what happens to the nests, what the mesh is made of, and how it is attached. The cheap job is the one we get called to redo.'),
        ('Are the spinners really free?', 'Two to three are included depending on the size of the roof. Extras are $50 each. A two story with panels on both sides usually wants one more so the flash reaches the back.'),
        ('Is the price firm?', 'Yes. The number in the tool above, or the one Tony texts you after a look, is the price. Nothing gets added on the day, including if the cleanout takes longer than expected.'),
        ('Is there a warranty?', 'Two years pigeon free, in writing. If they get back under the panels in that time, we come back.'),
    ],
})

PAGES.append({
    'fn': 'pigeon-proofing-without-drilling.html',
    'title': 'Pigeon Proofing Without Drilling: Clips, Not Screws | Tony\'s',
    'desc': 'Solar pigeon mesh held by clips on the panel frame, never screws or bolts. Nothing drilled, warranty intact, holds in High Desert wind. $450 up to 12 panels.',
    'og_image': OG('pigeon-proofing'), 'crumb': 'Clips, Not Screws', 'parent': ('Pigeon Proofing', S + 'pigeon-proofing.html'),
    'where': 'Serving Hesperia and the High Desert',
    'h1': 'Pigeon Proofing <span class="grad">Without Drilling</span>', 'tagline': 'Rigid steel mesh, clipped to the lip of the panel frame. No screws, no bolts, no holes in your panels or your roof.',
    'lede': 'There are two ways to hold pigeon mesh on a solar array. One drills or screws it into the panel frame or the roof. The other clips it to the frame\'s lip. The clipped way costs a little more in parts and takes more care to fit. It is the only way we do it, and this page is why.',
    'schema_name': 'Pigeon Proofing With Frame Clips', 'service_type': 'Solar panel pigeon proofing', 'price': '450.00',
    'price_desc': 'Pigeon proofing with rigid steel mesh clipped to the panel frame, up to 12 panels, cleanout and free spinners included.',
    'sections': [
        ('tiles', 'Clips or screws', 'What each one does to your roof',
         [('Screws through the frame', 'Every hole is a place water gets in and a reason for a solar company to deny a warranty claim. In High Desert wind the mesh works against the screw heads and loosens within a couple of seasons.'),
          ('Screws into the roof', 'Holes through tile or shingle underlayment, right next to the array where a leak is hardest to find. Nobody wants to explain that to a roofer.'),
          ('Clips on the frame lip', 'A steel clip grips the inner lip of the aluminum frame and pins the mesh to it. No penetration anywhere. It holds in wind, and it comes off clean if a panel ever needs service.')]),
        ('text', 'The mesh', 'What we clip on',
         ['Rigid, rust resistant steel mesh, not plastic and not chicken wire. Chicken wire rusts, sags and gets pushed aside by a bird that wants in. Plastic goes brittle in the sun. Steel mesh cut to the array and clipped every few inches stays flat and stays put.',
          'The mesh runs the full perimeter, including the corners and the gap at the top edge where installers leave room for airflow. Pigeons find a two inch gap in a day, so the perimeter gets walked twice before we leave.']),
        ('text', 'Warranty', 'Why your installer will be fine with it',
         ['Panel and installer warranties cover the module and the mounting. Drilling into either one gives them a reason to walk away from a claim. Clips touch the frame lip and nothing else, so there is nothing to argue about. If a panel ever has to come out for service, the clips release and go back on afterward.',
          'We include a 2 year pigeon free warranty of our own, in writing, on every job.']),
        ('text', 'The rest of the job', 'What comes with the mesh',
         ['The birds are cleaned out first: nests, eggs, droppings and debris hauled off, and the area sanitized so the smell goes. Then the mesh, then 2 to 3 reflective spinners on the roof vents, held with hose clamps, no drilling there either. The panels get washed with purified water and the roof gets a soft wash, both free with the job.',
          '$450 covers up to 12 panels, $50 for each panel over. The 3D above shows the mesh going on and what the spinners cover.']),
        ('photos', 'Our work', 'Mesh clipped on, nothing drilled', 'Our own photos from High Desert roofs.',
         [('assets/photos/hub-pigeon-proofing-02.jpg', 'Steel mesh clipped along the full edge of a solar array'),
          ('assets/photos/hub-pigeon-proofing-03.jpg', 'Close view of pigeon mesh held by frame clips'),
          ('assets/photos/hesperia-pigeon-04.jpg', 'Pigeon proofed solar array on a Hesperia roof'),
          ('assets/photos/victorville-pigeon-01.jpg', 'Sealed solar array in Victorville')]),
        ('cta', 'Closed off, <span class="grad">nothing drilled</span>', 'Set your panel count above and see the mesh go on in 3D.', 'Get my price'),
    ],
    'faq_title': 'Clips and drilling questions',
    'faq': [
        ('Do you drill into the panels or the roof?', 'No. The mesh is held by steel clips that grip the inner lip of the panel frame. Spinners mount on the roof vents with hose clamps. Nothing gets a hole.'),
        ('Do the clips hold in the wind?', 'Yes. The clip pins the mesh against the frame lip, so wind pushes the mesh into the clip rather than away from it. Screwed mesh is the kind that works loose, because the mesh flexes against the screw heads until they strip.'),
        ('Will this affect my solar warranty?', 'Clips touch the frame lip and nothing else, so there is no penetration for a manufacturer or installer to point at. Screws through the frame or the roof are exactly what they point at.'),
        ('What if a panel needs service later?', 'The clips release by hand, the mesh section comes away, the panel is serviced, and the mesh goes back on. Nothing to patch afterward.'),
        ('Is chicken wire ever okay?', 'No. It rusts, it sags, and a pigeon pushes it aside. Rigid steel mesh cut to the array is the only material we install.'),
    ],
})

PAGES.append({
    'fn': 'pigeon-droppings-cleanup.html',
    'title': 'Pigeon Droppings and Nest Cleanup, High Desert | Tony\'s',
    'desc': 'Pigeon droppings and nests removed from roofs and under solar panels, hauled off and the area sanitized so the smell goes too. Included with pigeon proofing.',
    'og_image': OG('pigeon-proofing'), 'crumb': 'Droppings Cleanup', 'parent': ('Pigeon Proofing', S + 'pigeon-proofing.html'),
    'where': 'Serving Hesperia and the High Desert',
    'h1': 'Pigeon Droppings and <span class="grad">Nest Cleanup</span>', 'tagline': 'Nests out, droppings off, the area sanitized so the smell leaves with them. Included in every pigeon proofing job.',
    'lede': 'The droppings are what people notice first, on the tile, down the wall, on the driveway. The smell is what they notice second, and nobody warns them about it. A year of nesting under a solar array gives off a sharp ammonia smell that comes through the attic vents on a hot afternoon. The cleanout takes care of both.',
    'schema_name': 'Pigeon Droppings and Nest Cleanup', 'service_type': 'Bird dropping cleanup', 'price': '450.00',
    'price_desc': 'Nest and dropping cleanout under solar panels with sanitizing, included in pigeon proofing from $450.',
    'sections': [
        ('text', 'The cleanout', 'What comes out and how',
         ['Every panel edge is opened up and the nesting material comes out: sticks, feathers, eggs, dead birds when there are any, and the packed droppings underneath. It goes into bags on the roof and off the roof, not swept onto the yard. Then the roof deck, the tile and the panel undersides get scraped and washed.',
          'We wear respirators for this and so should anyone doing it. Dried droppings go airborne when disturbed, and that dust is the part that is actually bad for you.']),
        ('tiles', 'What gets treated', 'Three places the mess ends up',
         [('Under the panels', 'The nests themselves and a layer of droppings on the roof deck that nobody can see from the ground. This is where the smell lives.'),
          ('Tile and stucco', 'Droppings are acidic. Fresh ones wash off. A year old on concrete tile, some of the discoloration has gone into the surface, and we tell you what will not come back.'),
          ('Driveway and patio', 'The white streaks under the eaves. A soft wash takes them off concrete and pavers as part of the roof wash.')]),
        ('text', 'Sanitizing', 'Why washing is not enough',
         ['Washing moves the visible mess. Sanitizing kills what is left in the cracks of the tile and the grain of the roof deck, which is where the smell keeps coming from after a plain rinse. We treat the nesting area and the runoff path, then rinse. On a hot day the difference is obvious within a week.',
          'A roof soft wash is included with pigeon proofing, low pressure so tile and shingle are not damaged, and it takes the streaks off everything below the array too.']),
        ('text', 'Then keep them out', 'A cleanout without proofing is temporary',
         ['Pigeons come back to a roost, and the ones that hatched under your panels think of your roof as home. Cleaning without closing the array off buys a few weeks. That is why we do not sell the cleanout on its own: it is part of pigeon proofing, with rigid mesh clipped to the panel frame and 2 to 3 free spinners so they do not settle again.',
          '$450 covers up to 12 panels, $50 a panel after that, cleanout, mesh, spinners, panel wash and roof wash included. Set your count above to see your price.']),
        ('photos', 'Our work', 'Before the mesh goes on', 'Our own photos from High Desert roofs.',
         [('assets/photos/hesperia-pigeon-01.jpg', 'Solar array in Hesperia after cleanout and mesh'),
          ('assets/photos/apple-valley-pigeon-03.jpg', 'Apple Valley roof cleaned and sealed'),
          ('assets/photos/oak-hills-pigeon-05.jpg', 'Oak Hills array closed off after a cleanout'),
          ('assets/photos/phelan-pigeon-02.jpg', 'Pigeon proofed array in Phelan')]),
        ('cta', 'The mess gone, the <span class="grad">smell with it</span>', 'Set your panel count above. Cleanout, mesh and spinners are all in the price.', 'Get my price'),
    ],
    'faq_title': 'Droppings cleanup questions',
    'faq': [
        ('Do you clean up the droppings or just install mesh?', 'Both, always. The nests, droppings and debris come out from under every panel and get hauled off, the area is sanitized, then the mesh goes on. Mesh over a dirty roof seals the smell in.'),
        ('Will the smell go away?', 'Yes, once the nesting material is out and the area is sanitized. Washing alone leaves it in the tile and the roof deck. If a smell lingers after a hot week, call and we come back.'),
        ('Will the stains on my tile come off?', 'Fresh droppings come off completely. Droppings that have sat on concrete tile for a year or more have etched into the surface a little, and some shadow can remain. We tell you before we start what to expect.'),
        ('Is pigeon droppings dust dangerous?', 'Disturbed dry droppings can carry things you do not want to breathe, which is why we wear respirators for the cleanout and bag everything on the roof instead of sweeping it off. You do not need to be home for it and you do not want to be under it.'),
        ('Can I just have the cleanout without the mesh?', 'We do not offer it on its own, because the birds come back within weeks and you pay twice. The cleanout is part of pigeon proofing, which closes the array off and keeps them away.'),
    ],
})
