# Page specs, English, part 2: windows. Written by hand for each question.
S = 'https://twindowclean.com/'
OG = lambda n: S + 'assets/og/' + n + '.jpg'

PAGES = []

PAGES.append({
    'fn': 'hard-water-stains-windows.html',
    'title': 'Hard Water Stains on Windows: Causes and the Fix | Tony\'s',
    'desc': 'Why sprinklers leave white spots on High Desert windows, the three stages of hard water staining, and what comes off. One pane tested free, from $12 a pane.',
    'og_image': OG('hard-water-removal'), 'crumb': 'Hard Water Stains', 'parent': ('Hard Water Removal', S + 'hard-water-removal.html'),
    'where': 'Serving Hesperia and the High Desert',
    'h1': 'Hard Water Stains on <span class="grad">Windows</span>', 'tagline': 'Where the white spots come from, which stage yours are at, and what a normal clean will not touch. One pane tested free.',
    'lede': 'The cloudy band along the bottom of a window, always on the side that faces the lawn, is not dirt. It is minerals from sprinkler water that dried on the glass, one cycle at a time, until they bonded to it. Windex will not move it and neither will a regular window cleaning. Here is what will.',
    'schema_name': 'Hard Water Stain Removal from Windows', 'service_type': 'Hard water stain removal', 'price': '12.00',
    'price_desc': 'Hard water stain removal, treated and polished pane by pane, from $12 a pane, one pane tested free.',
    'sections': [
        ('text', 'The cause', 'Why it happens more up here',
         ['High Desert water is hard, and sprinkler heads on a windy morning throw it onto the glass a few feet away. Every cycle leaves a film of calcium and magnesium as the droplets dry. In summer the glass is hot, the water evaporates in minutes, and the minerals bake on before anyone sees them.',
          'It shows up on the same windows in every neighborhood: the ones by the lawn in Spring Valley Lake, the course side homes at Hesperia Golf and Country Club, the front windows behind a parkway strip in Victorville. Drip irrigation homes almost never get it.']),
        ('tiles', 'The stages', 'Which one yours is at',
         [('Stage one: surface film', 'A haze you can feel with a fingernail. It comes off in a normal cleaning with the right technique and a little more time. If your windows are here, book a window cleaning and it is handled.'),
          ('Stage two: bonded spots', 'White rings that stay after a wash. The minerals have bonded to the glass and need a restoration compound worked in by hand, pane by pane. This is the $12 a pane work, and it comes off.'),
          ('Stage three: etching', 'The minerals have eaten into the surface. Polishing brings back most of the clarity but not all, because the glass itself is pitted. We test a pane first and tell you honestly what to expect.')]),
        ('text', 'The fix', 'How we take it off',
         ['A restoration compound is worked into the glass by hand with a pad, pane by pane, then rinsed with purified water and squeegeed. It is slow work and it is priced that way: from $12 a pane, added to an exterior window clean. Before you pay for anything we treat one pane free so you see the result on your own glass.',
          'Then the cause has to be fixed or the spots come back. Usually it is one sprinkler head turned two inches. We point out which one.']),
        ('text', 'Price', 'What hard water removal costs',
         ['From $12 a pane on top of the window cleaning, and only the panes that need it. A typical home has four to eight affected panes, so the add on is usually $48 to $96. One pane tested free first, every time. Book on our website and the visit is 10% off.',
          'Set the pane count in the tool above. It rides along with the window cleaning line so the total is the whole visit.']),
        ('cta', 'One pane tested <span class="grad">free</span>', 'Add hard water removal above and count the panes with spots.', 'Get my price'),
    ],
    'faq_title': 'Hard water stain questions',
    'faq': [
        ('Will a regular window cleaning remove hard water stains?', 'Surface film, yes. Bonded white spots, no. Those need a restoration compound worked in by hand, which is separate work priced by the pane. We test one pane free so you know which stage you are at before spending anything.'),
        ('Can hard water stains be removed completely?', 'Stage one and two, yes. Stage three, where the minerals have etched the glass, polishing brings back most of the clarity but the pitting stays. We show you on the test pane and you decide.'),
        ('What causes the spots on my windows?', 'Sprinkler overspray. Hard water dries on hot glass, leaves minerals behind, and every cycle adds a layer. It is almost always the windows nearest a lawn or a parkway strip, and it almost never happens on drip irrigation homes.'),
        ('How much does it cost?', 'From $12 a pane, added to an exterior window clean, and only for the panes that need it. Most homes are four to eight panes. One pane is tested free first.'),
        ('How do I keep it from coming back?', 'Adjust the sprinkler head that reaches the glass, usually one or two of them, or switch that zone to drip. We point out which heads are hitting the windows while we are there.'),
    ],
})

PAGES.append({
    'fn': 'window-cleaning-two-story.html',
    'title': 'Two Story Window Cleaning, $249 | Tony\'s Window Cleaning',
    'desc': 'Two story window cleaning for $249 in the High Desert: water fed pole with purified water, no ladders on your stucco, screens, tracks and sills included.',
    'og_image': OG('window-cleaning'), 'crumb': 'Two Story Homes', 'parent': ('Window Cleaning', S + 'window-cleaning.html'),
    'where': 'Serving Hesperia and the High Desert',
    'h1': 'Two Story <span class="grad">Window Cleaning</span>', 'tagline': '$249 for the outside of a two story home, 18 to 20 windows, screens, tracks and sills included. No ladders leaning on your stucco.',
    'lede': 'Upstairs windows are the ones that never get done, because nobody wants to stand on a ladder over a rock yard. We clean them from the ground with a water fed pole and purified water, the same way the panels get washed, and the upstairs glass comes out as clean as the downstairs.',
    'schema_name': 'Two Story Window Cleaning', 'service_type': 'Residential window cleaning', 'price': '249.00',
    'price_desc': 'Exterior window cleaning for a two story home, 18 to 20 windows, screens, tracks and sills included.',
    'sections': [
        ('tiles', 'How it is done', 'Upstairs glass without a ladder',
         [('Water fed pole', 'A carbon fiber pole with a soft brush on the end reaches second story glass from the ground. Purified water is pumped up through it, the brush scrubs, and the rinse dries spot free because there is nothing in the water to leave a spot.'),
          ('Purified water', 'Tap water dries into mineral spots, which is why hosing windows never works. Deionized water carries nothing, so the glass dries clear with no squeegee and no wiping needed up high.'),
          ('Screens and tracks', 'Upstairs screens come out from the inside, get scrubbed and go back. Tracks and sills on the ground floor are wiped out, and the upstairs sills are rinsed clean.')]),
        ('text', 'Why no ladders', 'What ladders do to a two story home',
         ['A ladder on stucco leaves two scuffs where it rests and sometimes a crack. On rock yards it walks, on slopes it tips, and on a windy Hesperia afternoon it is dangerous for the person on it. The pole does the same window from the ground in less time and touches nothing but the glass.',
          'Where a pole cannot reach, a bay window over a garage roof for example, we work from the roof deck or bring a ladder with standoffs that keep it off the wall. That is rare on tract homes and we tell you ahead of time if yours needs it.']),
        ('text', 'What the price covers', 'What $249 includes and what it does not',
         ['$249 covers the outside of a two story home with 18 to 20 windows: glass, screens, tracks and sills. Past 20 windows it is a flat $39 more, one price no matter how many. Inside every window is $49 more, same visit, tracks vacuumed and wiped dry.',
          'A big custom two story, the kind with a two story entry and 30 windows across the back, is priced after a look and usually runs $499 to $599 inside and out. Tony confirms the number in writing before anything starts. Book on our website and the first visit is 10% off.']),
        ('text', 'Keeping it clean', 'How often a two story needs it',
         ['Upstairs glass gets less sprinkler overspray but more wind blown dust, and nobody notices it from inside until the sun hits it. Twice a year keeps it clear, and on a plan that is 15% off each visit after the first. Every 3 months is 25% off and is what homes on the open desert edge tend to pick.']),
        ('cta', 'Upstairs done, <span class="grad">no ladder</span>', 'Tap 2 story above and the price is your price.', 'Get my price'),
    ],
    'faq_title': 'Two story window cleaning questions',
    'faq': [
        ('How much does two story window cleaning cost?', '$249 for the outside of a two story home with 18 to 20 windows, screens, tracks and sills included. More than 20 windows is a flat $39 more. Inside every window is $49 more on the same visit.'),
        ('Do you use ladders on a two story?', 'Almost never. Second story glass is cleaned from the ground with a water fed pole and purified water, which leaves nothing on your stucco and nothing to spot. Where a pole cannot reach we work from a roof deck or use standoffs that keep the ladder off the wall.'),
        ('How do the upstairs screens get cleaned?', 'They come out from inside, get scrubbed and rinsed, and go back in. If you would rather we not come inside, the screens can be passed out and back through the window.'),
        ('Do you clean the upstairs tracks?', 'Sills upstairs are rinsed clean from the pole. Tracks are wiped out wherever we can reach them from inside, which is part of the inside windows add on at $49.'),
        ('What about a large custom two story?', 'Homes with two story entries and 25 to 30 plus windows are priced after a look, usually $499 to $599 inside and out. The number is confirmed in writing before we start and it does not change on the day.'),
    ],
})

PAGES.append({
    'fn': 'inside-window-cleaning.html',
    'title': 'Inside Window Cleaning and Track Cleaning, $49 | Tony\'s',
    'desc': 'Every interior window in the house for $49 on the same visit as the outside, with the tracks vacuumed and wiped dry. Hesperia, Victorville and Apple Valley.',
    'og_image': OG('window-cleaning'), 'crumb': 'Inside Windows', 'parent': ('Window Cleaning', S + 'window-cleaning.html'),
    'where': 'Serving Hesperia and the High Desert',
    'h1': 'Inside Windows and <span class="grad">Tracks</span>', 'tagline': 'Every interior window in the house for $49, same visit, tracks vacuumed and wiped dry. The part most crews skip.',
    'lede': 'After most crews clean the outside, the wash water runs down into the track and sits there as a muddy puddle. You open the window a week later and the gunk is still there. The inside add on is where that gets fixed, and it is one flat $49 for the whole house, not a price per window.',
    'schema_name': 'Interior Window and Track Cleaning', 'service_type': 'Interior window cleaning', 'price': '49.00',
    'price_desc': 'Every interior window in the home cleaned on the same visit, tracks vacuumed and wiped dry.',
    'sections': [
        ('tiles', 'What is included', 'Three things, every window',
         [('Inside glass', 'Purified water and a squeegee on the inside pane, edges detailed with a cloth so nothing runs onto the sill.'),
          ('Tracks vacuumed and wiped', 'The track is vacuumed first so the grit and dead bugs come out dry, then wiped until the cloth comes up clean. Windows slide the way they did when the house was new.'),
          ('Sills and frames', 'Interior sills wiped, frames wiped, and the corners where the dust piles up done by hand.')]),
        ('text', 'Why one price', 'Why it is $49 and not per window',
         ['Most companies price inside work by the window because it takes longer than the outside. We are already at your house with the water and the tools, so the inside is added labor, not a second trip. One flat $49 for a single story or a two story means you never have to count windows or wonder if the bathroom one is extra.',
          'It also means the tracks get done properly instead of skipped to hit a per window price. The track is the slow part and the part you feel every time you open a window.']),
        ('text', 'How the visit goes', 'What to expect inside',
         ['Shoes off or covered, drop cloths under the windows we are working on, and blinds raised and lowered with care. We start upstairs if there is one and work down, so nothing drips onto finished glass. Furniture gets moved a foot and put back. A single story with 12 windows takes about an hour inside.',
          'If there is a room you would rather we skip, say so and it is skipped, with no change to the price.']),
        ('text', 'Price', 'What it costs with the outside',
         ['$149 for the outside of a single story or $249 for a two story, plus $49 for every inside window and track. So a single story inside and out is $198, a two story is $298. Book on our website and the visit is 10% off. On a twice a year plan the visits after the first are 15% off, every 3 months 25% off.',
          'Turn on Inside windows too in the tool above and the total updates. The 3D shows the track work if you want to see what the $49 buys.']),
        ('cta', 'Windows that <span class="grad">slide clean</span>', 'Turn on Inside windows above and see the whole visit priced.', 'Get my price'),
    ],
    'faq_title': 'Inside window cleaning questions',
    'faq': [
        ('How much is inside window cleaning?', '$49 for every interior window in the house, single story or two story, on the same visit as the outside. The tracks are vacuumed and wiped dry as part of it.'),
        ('Do you clean the window tracks?', 'Yes, and it is the point of the add on. Tracks are vacuumed first so the grit comes out dry, then wiped clean. Most crews rinse the outside and leave the water sitting in the track as mud.'),
        ('Do I need to be home?', 'For inside work, yes, or someone who can let us in. Outside only can be done with nobody home and the gate unlocked.'),
        ('Do you move furniture?', 'Anything light gets moved a foot and put back. Heavy pieces stay and we reach behind them. Drop cloths go under every window we work on and shoes are off or covered.'),
        ('Can I do inside only?', 'Inside windows are an add on to an exterior clean. The tool above adds them to the outside price, which is where the value is, because we are already there with the water and the tools.'),
    ],
})

PAGES.append({
    'fn': 'window-cleaning-maintenance-plan.html',
    'title': 'Window Cleaning Plans: Twice a Year or Quarterly | Tony\'s',
    'desc': 'Recurring window cleaning in the High Desert, priced: once a year regular price, twice a year 15% off, every 3 months 25% off, and a text before every visit.',
    'og_image': OG('window-cleaning'), 'crumb': 'Window Cleaning Plans', 'parent': ('Window Cleaning', S + 'window-cleaning.html'),
    'where': 'Serving Hesperia and the High Desert',
    'h1': 'Window Cleaning <span class="grad">Plans</span>', 'tagline': 'Twice a year is 15% off every visit after the first. Every 3 months is 25% off. Tony texts before each one, and there is nothing to cancel.',
    'lede': 'Desert dust and hard water come back the way a lawn grows back. The homes that always look clean are not the ones that clean harder, they are the ones on a schedule. Here is what each schedule costs on a real house and which one fits which street.',
    'schema_name': 'Recurring Window Cleaning Plan', 'service_type': 'Residential window cleaning', 'price': '149.00',
    'price_desc': 'Exterior window cleaning on a schedule: once a year regular price, twice a year 15% off, every 3 months 25% off each visit after the first.',
    'sections': [
        ('tiles', 'The three plans', 'Priced on a single story at $149',
         [('Once a year', '$149 each visit. Tony texts when it is due. Right for shaded, sheltered homes and anyone who just wants the reminder.'),
          ('Twice a year: 15% off', '$149 the first visit, then $126.65 each. Spring after the wind season and fall after the summer heat. About $275 for the year. The most common pick in Victorville and Apple Valley tracts.'),
          ('Every 3 months: 25% off', '$149 the first visit, then $111.75 each. About $484 a year against $596 booked one at a time. The right one for homes by open desert, dirt roads or sprinklers, where glass never gets the chance to etch.')]),
        ('text', 'Two story and inside', 'The same math on other homes',
         ['A two story at $249 is $211.65 a visit on the twice a year plan and $186.75 every 3 months. Inside windows at $49 are discounted the same way when they are on the plan. Solar panels can ride along on the same schedule, and the solar line gets the same discount unless it is already free with pigeon proofing.',
          'The tool above does this arithmetic for your own house: set the services, then pick a plan and the visits are listed with dates and prices.']),
        ('text', 'How it works', 'What a plan is and is not',
         ['It is a schedule and a discount, not a contract. Tony texts you a few days before each visit with the day. Reply to move it or skip it. There is no card on file, no automatic charge and nothing to cancel. The price is locked for the year, so a price change during the year does not touch you.',
          'Book the first visit on our website and it is 10% off on top.']),
        ('text', 'Why it matters here', 'What the schedule prevents',
         ['Sprinkler minerals bond to glass within months in summer heat. Caught at three or six months they wash off in a normal cleaning. Left a year, they need hard water removal at $12 a pane, and left two years some of it is etched for good. Screens on a schedule get inspected before the mesh gives out, and tracks never get to the muddy stage. The plan is cheaper than the catch up.']),
        ('cta', 'Pick a plan, <span class="grad">forget about it</span>', 'Set your services above and choose a plan. The visits are priced and dated.', 'Get my price'),
    ],
    'faq_title': 'Window cleaning plan questions',
    'faq': [
        ('How often should windows be cleaned in the High Desert?', 'Twice a year for most tract homes, every 3 months for homes near open desert, dirt roads or sprinklers, and once a year at a minimum for sheltered homes. Dust and hard water build up faster up here than down the hill because there is so little rain.'),
        ('What does a plan cost?', 'Once a year is the regular price with a reminder. Twice a year is 15% off every visit after the first, every 3 months is 25% off. On a $149 single story that is $126.65 or $111.75 a visit.'),
        ('Is it a contract?', 'No. Tony texts before each visit and you can move or skip it. No card on file, no automatic charges, nothing to cancel.'),
        ('Can solar panels be on the same plan?', 'Yes. Panels ride along on the same visits and the solar line gets the same plan discount, unless the panels are already washed free as part of pigeon proofing.'),
        ('Is the price locked?', 'Yes, for the year. If prices change during your plan, your visits stay at the price you signed up at.'),
    ],
})

PAGES.append({
    'fn': 'window-cleaning-spring-valley-lake.html',
    'title': 'Window Cleaning in Spring Valley Lake | Tony\'s',
    'desc': 'Window cleaning in Spring Valley Lake from $149, with the lake side glass, sprinkler spots and big arched windows handled. Screens, tracks and sills included.',
    'og_image': OG('spring-valley-lake'), 'crumb': 'Spring Valley Lake', 'parent': ('Window Cleaning', S + 'window-cleaning.html'),
    'where': 'Serving Spring Valley Lake and the High Desert', 'area': [{'@type': 'City', 'name': 'Spring Valley Lake', 'address': {'@type': 'PostalAddress', 'addressLocality': 'Victorville', 'addressRegion': 'CA', 'postalCode': '92395', 'addressCountry': 'US'}}],
    'h1': 'Window Cleaning in <span class="grad">Spring Valley Lake</span>', 'tagline': 'From $149, screens, tracks and sills included. The lake side glass is the reason people call, and it is the glass we know best.',
    'lede': 'Spring Valley Lake homes have more glass than anywhere else in the High Desert: arched windows facing the water, sliders across the back, second story views over the fairways. They also have lawns and sprinklers, which is why so much of the glass here carries hard water spots by the end of summer.',
    'schema_name': 'Window Cleaning in Spring Valley Lake', 'service_type': 'Residential window cleaning', 'price': '149.00',
    'price_desc': 'Exterior window cleaning from $149 single story, $249 two story, screens, tracks and sills included.',
    'sections': [
        ('text', 'The lake side', 'What is different about SVL glass',
         ['Waterfront homes get spray and humidity off the lake on the back side and sprinkler overspray on the front, so the two sides of the house need different attention. Lake side glass carries a film that a purified water rinse takes off easily. Street side glass by the lawn is where the mineral spots live.',
          'Arched and tall windows are cleaned from the ground with a water fed pole. No ladders leaning on the stucco, and the arch tops, which most crews never reach properly, get scrubbed and rinsed the same as the rest.']),
        ('tiles', 'Around the lake', 'Three kinds of SVL homes',
         [('Waterfront', 'Big rear glass, often two stories of it, and docks that make the back hard to reach from the yard. The pole reaches from the patio and the dock side is done from the water\'s edge.'),
          ('Golf course', 'Fairway facing windows get sprinkler overspray from the course as well as the yard. Hard water spots here are the rule, and we test one pane free before pricing the removal.'),
          ('Interior streets', 'Standard tract windows with lawns out front. $149 single story, $249 two story, and the plan discounts if you want it kept up.')]),
        ('text', 'Price', 'What window cleaning costs in Spring Valley Lake',
         ['$149 for a single story, $249 for a two story, screens, tracks and sills included. Homes with more than 12 windows on one story or 20 on two stories are a flat $39 more. Inside every window is $49. Hard water spots are from $12 a pane, one pane tested free. The large custom waterfront homes are priced after a look and confirmed in writing.',
          'Book on our website and the first visit is 10% off. No trip fee anywhere in SVL.']),
        ('cta', 'Lake view, <span class="grad">clear glass</span>', 'Set your home above. Pick Large two story and the lake street in the 3D to see one like yours.', 'Get my price'),
    ],
    'faq_title': 'Spring Valley Lake window questions',
    'faq': [
        ('Do you clean the windows on the lake side?', 'Yes, including the tall and arched glass, from the patio or the dock side with a water fed pole. No ladders on the stucco.'),
        ('What does window cleaning cost in Spring Valley Lake?', '$149 single story, $249 two story, screens, tracks and sills included. Large waterfront homes with 25 or more windows are priced after a look, usually $499 to $599 inside and out, confirmed in writing.'),
        ('Can you remove the sprinkler spots?', 'Yes. Hard water removal is from $12 a pane, added to the window cleaning, and we treat one pane free first so you see the result before paying for the rest.'),
        ('Do you do the arched windows?', 'Yes, the arch tops get the same scrub and rinse as the rest. The pole reaches them from the ground and the purified water dries clear up high with nothing to wipe.'),
        ('How often should lakefront glass be cleaned?', 'Twice a year keeps most SVL homes clear, every 3 months for waterfront glass that takes lake spray. On a plan those visits are 15% or 25% off after the first.'),
    ],
})

PAGES.append({
    'fn': 'window-cleaning-silverwood.html',
    'title': 'Window Cleaning in Silverwood, Hesperia | Tony\'s',
    'desc': 'Window cleaning in Silverwood from $149, including the first clean after move in when builder dust and sticker residue are still on the glass. No trip fee.',
    'og_image': OG('silverwood'), 'crumb': 'Silverwood', 'parent': ('Window Cleaning', S + 'window-cleaning.html'),
    'where': 'Serving Silverwood and Hesperia', 'area': ['Silverwood, Hesperia, CA', 'Hesperia, CA'],
    'h1': 'Window Cleaning in <span class="grad">Silverwood</span>', 'tagline': 'From $149, screens, tracks and sills included. New homes, new glass, and a first clean that gets the builder\'s dust off for good.',
    'lede': 'Silverwood is the newest community in the High Desert, which means new windows with a specific problem: construction dust in every track, sticker residue on the panes and stucco spatter along the bottom edge. A normal clean handles most of it. The rest needs the new construction clean, and this page explains which one you need.',
    'schema_name': 'Window Cleaning in Silverwood', 'service_type': 'Residential window cleaning', 'price': '149.00',
    'price_desc': 'Exterior window cleaning from $149 single story, $249 two story, screens, tracks and sills included.',
    'sections': [
        ('tiles', 'New homes', 'What Silverwood glass usually needs',
         [('First month in', 'Tracks full of drywall dust and sawdust, panes with a haze from the builder\'s final rinse. A regular clean with the inside add on clears it, because the tracks get vacuumed dry.'),
          ('Sticker residue', 'The manufacturer labels come off and leave adhesive squares that collect dust. Those are scraped safely as part of the new construction clean, after testing that the glass is not tempered on that pane.'),
          ('Stucco and paint', 'Spatter along the bottom edge of the glass from the finish work. Also new construction clean territory, $249 for a single story inside and out, $349 for a two story.')]),
        ('text', 'Which service', 'Regular clean or new construction clean',
         ['If the house has been lived in for a while and the glass just has desert dust and a few spots, it is a regular window cleaning at $149 or $249 outside, $49 more for inside and tracks. If there is still residue, spatter or paint on the panes from the build, it is the new construction clean, which includes inside and out and the careful scraping that residue needs.',
          'Not sure which? Text a photo of one pane to 714-559-0300 and Tony will tell you, or book the regular clean and we upgrade it on site only if it is needed, with the price confirmed first.']),
        ('text', 'The community', 'Working in Silverwood',
         ['Homes here are close together with new rock yards and young trees, so wind blown dust reaches every window and there is not much shade yet. Twice a year keeps the glass clear, and the every 3 months plan is worth it on homes at the edges facing open desert. Gate access and builder hours are never a problem because we schedule around them.',
          'Hesperia is home base, so Silverwood is minutes away and there is no trip fee.']),
        ('text', 'Price', 'What it costs in Silverwood',
         ['$149 single story, $249 two story, screens, tracks and sills included. Inside every window and track $49. New construction clean $249 single story or $349 two story, inside and out. Book on our website and the first visit is 10% off.']),
        ('cta', 'New home, <span class="grad">clear glass</span>', 'Pick New build in the 3D above and see the job on a home like yours.', 'Get my price'),
    ],
    'faq_title': 'Silverwood window questions',
    'faq': [
        ('Do you come to Silverwood?', 'Yes, it is a few minutes from home base in Hesperia. No trip fee, and no charge to come and look.'),
        ('My windows still have sticker residue from the builder. Which service is that?', 'The new construction clean, $249 single story or $349 two story inside and out. It includes safe scraping of residue, stucco spatter and paint after checking whether each pane is tempered.'),
        ('What does a regular window cleaning cost here?', '$149 single story, $249 two story, screens, tracks and sills included. Inside windows and tracks are $49 more for the whole house.'),
        ('How often do new homes need it?', 'Twice a year for most of the community. Homes on the edges facing open desert and young yards without shade do better every 3 months, which is 25% off each visit on a plan.'),
        ('Can you get in past the gate?', 'Yes. We schedule the day with you and get the gate code or meet you there, the same as anywhere else.'),
    ],
})

PAGES.append({
    'fn': 'new-construction-window-cleaning-silverwood.html',
    'title': 'New Construction Window Cleaning in Silverwood | Tony\'s',
    'desc': 'Builder clean for new Silverwood homes: sticker residue, stucco spatter and paint off the glass inside and out, tempered panes tested first. $249 a home.',
    'og_image': OG('post-construction-window-cleaning'), 'crumb': 'Silverwood New Homes', 'parent': ('New Construction Window Cleaning', S + 'post-construction-window-cleaning.html'),
    'where': 'Serving Silverwood and Hesperia', 'area': ['Silverwood, Hesperia, CA', 'Hesperia, CA'],
    'h1': 'New Construction Window Cleaning in <span class="grad">Silverwood</span>', 'tagline': 'The first real clean your new windows get. Residue, spatter and paint off, inside and out, $249 single story and $349 two story.',
    'lede': 'The builder\'s final clean is a quick wipe before the walk through. What it leaves behind shows up the first sunny morning: adhesive squares where the labels were, stucco freckles along the bottom of every pane, a fine drywall dust in the tracks. This is the clean that actually finishes the house.',
    'schema_name': 'New Construction Window Cleaning in Silverwood', 'service_type': 'Post construction window cleaning', 'price': '249.00',
    'price_desc': 'New construction window cleaning inside and out, $249 single story, $349 two story, tempered panes tested before scraping.',
    'sections': [
        ('text', 'What comes off', 'The three things on new glass',
         ['Label adhesive: the manufacturer stickers peel but leave a square of glue that grabs dust. Stucco spatter: the finish coat flicks onto the lower glass and dries hard. Paint and caulk: overspray at the edges from the trim work. None of it moves with a squeegee. It needs a solvent for the glue, a blade for the spatter, and care with both.']),
        ('tiles', 'How we do it safely', 'Why the blade is not the first tool',
         [('Tempered glass test', 'Tempered panes can have fabrication debris fused to the surface, and a blade drags it and scratches. Every pane is checked for the tempered stamp before any scraping, and tempered glass gets solvent and a pad instead.'),
          ('Wet, never dry', 'A blade is only used on wet glass with plenty of purified water under it, one direction, with the edge changed often. Dry scraping is how new windows get ruined.'),
          ('Inside and out', 'The inside faces have the same dust and often finger prints from the trades. Both sides are done and the tracks are vacuumed before they are wiped, so the drywall dust comes out dry.')]),
        ('text', 'Price', 'What the builder clean costs',
         ['$249 for a single story, $349 for a two story, inside and out, screens, tracks and sills included. That is the whole house, not a per pane price. Book on our website and it is 10% off. After that first clean, the regular $149 or $249 exterior clean is all the house needs.',
          'If the builder\'s clean was better than most and there is no residue, we say so on arrival and do the regular clean at the regular price instead.']),
        ('text', 'Timing', 'When to book it',
         ['After the last trade has left and before the furniture is against the windows, ideally the week you get keys. If you have been in a few months already, it still works; the residue is just a little more stubborn and the tracks a little fuller.']),
        ('cta', 'Finish the <span class="grad">new house</span>', 'Pick New construction clean in the tool above. One price, inside and out.', 'Get my price'),
    ],
    'faq_title': 'New construction window questions',
    'faq': [
        ('What is different about a new construction window clean?', 'It removes what the build left behind: label adhesive, stucco spatter, paint and caulk overspray, and drywall dust in the tracks. That takes solvents and careful blade work a regular cleaning does not include.'),
        ('Will scraping scratch my new windows?', 'Not done properly. Every pane is checked for the tempered stamp first, tempered glass is never scraped, and the rest is only scraped wet with purified water under the blade in one direction. Dry scraping is what causes scratches.'),
        ('How much is it?', '$249 for a single story, $349 for a two story, inside and out, screens, tracks and sills included. If the glass turns out to need only a regular clean, that is what you pay.'),
        ('When should I book it?', 'The week you get the keys, before furniture is against the glass. It still works months later, the residue is just a little more set.'),
        ('Do you do the inside too?', 'Yes, both faces of every window and the tracks vacuumed dry. New construction clean is priced as an inside and out job.'),
    ],
})

PAGES.append({
    'fn': 'hesperia-window-cleaning-reviews.html',
    'title': 'Tony\'s Window Cleaning Reviews, Hesperia | 5.0 on Google',
    'desc': 'What High Desert customers say about Tony\'s Window Cleaning: 5.0 stars across 25 Google reviews for windows, solar panels, pigeon proofing and hard water.',
    'og_image': OG('reviews'), 'crumb': 'Hesperia Reviews', 'parent': ('Reviews', S + 'reviews.html'),
    'where': 'Hesperia, home base since day one',
    'h1': 'Tony\'s Window Cleaning <span class="grad">Reviews</span>, Hesperia', 'tagline': '5.0 stars across 25 Google reviews. The words are the customers\' own, and every one of them describes a real job.',
    'lede': 'Tony\'s Window Cleaning is based in Hesperia and works across the High Desert and down the hill. The reviews below come straight from the Google listing. We do not edit them, we do not pay for them, and the ones that mention a hiccup are as useful to us as the ones that do not.',
    'schema_name': 'Tony\'s Window Cleaning, Hesperia', 'service_type': 'Window cleaning, solar panel cleaning and pigeon proofing', 'price': None,
    'sections': [
        ('tiles', 'In their words', 'Windows and solar',
         [('Mike S., Google review', '"Tony did an excellent job cleaning my windows as well as my solar panels."'),
          ('Staci M., Google review', '"Tony did a great job and even cleaned the solar panels."'),
          ('Chelsi, Google review, Fontana', '"They came out and cleaned our solar panels in Fontana and did a great job! He was professional and very kind. The panels are so clean and look awesome."')]),
        ('tiles', 'In their words', 'Pigeon proofing and roofs',
         [('Henry R., Google review', '"Tony is a first class guy, very nice and professional. Cleaned all the solar panels, bird-proofed and sealed broken tiles, and pressure washed the whole roof. Got the job done in one day at the best price."'),
          ('Oswaldo F., Google review', '"I hired Tony\'s Window Cleaning to come out and clean my 10 solar panels and pigeon proof them. He even installed reflective spinners to keep them off of my roof. I recommend them to any one looking to get their solar pigeon proofed in the High Desert."'),
          ('Hailey B., Google review', '"Tony did a great job on my roof it was left super clean how I expected I loved it! He cleaned my solar panels and whole roof, installed wire around the panels and he also installed the spinners for the pigeons."')]),
        ('text', 'What keeps coming up', 'The four things people mention without being asked',
         ['One visit, everything done. Panels, mesh, tile repair and a roof wash in a single day comes up more than once, because we schedule the day so it all fits and one truck roll is cheaper for you.',
          'The price matched the quote. Hard water removal, pigeon proofing and window cleaning reviews all say some version of reasonable price and the number did not move.',
          'Professional and kind. That is Tony on the roof and Tony on the phone, because it is the same person.',
          'Clean after. Concrete rinsed, droppings gone, nothing left in the yard. Hailey said it best: left super clean.']),
        ('text', 'Hard water', 'The review that says the most in the fewest words',
         ['Pam S., Google review: "Did great job. All hard water stains gone. Very professional and thorough. Will use again. Reasonable price." Hard water removal is the service people are most skeptical about, because they have tried everything from the hardware store first. One pane is always tested free so the result speaks before the price does.']),
        ('text', 'Leave your own', 'If we have worked for you',
         ['A review on Google is the single most useful thing a customer can do for a small local business, and we read every one. The link is in the footer of every page. If something was not right, text 714-559-0300 first and it gets fixed before anything else.']),
        ('cta', 'See why the stars are <span class="grad">all five</span>', 'Build your own quote above. The price is firm before we start.', 'Get my price'),
    ],
    'faq_title': 'Review questions',
    'faq': [
        ('Where do these reviews come from?', 'The Google Business listing for Tony\'s Window Cleaning in Hesperia. They are quoted as written. The full set of 25 is on Google, linked in the footer.'),
        ('Are they from Hesperia customers?', 'They are from customers across the High Desert and the Inland Empire. Tony\'s Window Cleaning is based in Hesperia, and most of the work is in Hesperia, Victorville, Apple Valley and the surrounding cities.'),
        ('Do you pay for or filter reviews?', 'No. We ask happy customers to leave one and we never pay, gate or filter. Anything that went wrong gets fixed first, then we ask.'),
        ('What do people mention most?', 'Getting everything done in one visit, the price matching the quote, and a clean roof and yard afterward. Those three come up again and again.'),
        ('How do I leave a review?', 'The Google review link is in the footer of every page on this site, or search Tony\'s Window Cleaning Hesperia on Google and tap Write a review.'),
    ],
})
