# Páginas en español. Escritas a mano, no traducidas palabra por palabra. Mismos precios que el sitio en inglés.
S = 'https://twindowclean.com/'
OG = lambda n: S + 'assets/og/' + n + '.jpg'

HD = ['Hesperia, CA', 'Victorville, CA', 'Apple Valley, CA', 'Adelanto, CA', 'Oak Hills, CA', 'Phelan, CA', 'High Desert', 'Inland Empire']

PAGES = []

PAGES.append({
    'fn': 'espanol.html', 'lang': 'es',
    'title': 'Limpieza de ventanas y paneles solares en Hesperia | Tony\'s',
    'desc': 'Limpieza de ventanas desde $149, paneles solares a $7 por panel y control de palomas desde $450 en Hesperia, Victorville y Apple Valley. Cotiza en español.',
    'og_image': OG('index'), 'crumb': None, 'parent': None, 'alts': [('en', 'index.html'), ('es', 'espanol.html'), ('x-default', 'index.html')],
    'where': 'Hesperia y todo el High Desert', 'area': HD,
    'h1': 'Ventanas, paneles solares y <span class="grad">palomas</span>, con precio antes de llamar',
    'tagline': 'Ventanas desde $149. Paneles solares a $7 cada uno. Control de palomas desde $450. Arma tu cotización aquí mismo y mírala en 3D en una casa como la tuya.',
    'lede': 'Tony\'s Window Cleaning es una empresa de Hesperia que trabaja en todo el High Desert y baja al Inland Empire. Los precios están publicados, la inspección es gratis y el precio que ves es el precio que pagas. Puedes escribirle a Tony en español por mensaje de texto.',
    'schema_name': 'Tony\'s Window Cleaning, servicios en español', 'service_type': 'Limpieza de ventanas, paneles solares y control de palomas', 'price': '149.00',
    'price_desc': 'Limpieza exterior de ventanas desde $149 en un piso, mosquiteros, rieles y repisas incluidos.',
    'sections': [
        ('tiles', 'Servicios', 'Lo que hacemos, con el precio a la vista',
         [('Ventanas: $149 y $249', 'Por fuera, un piso $149 y dos pisos $249, con mosquiteros, rieles y repisas incluidos. Por dentro, todas las ventanas de la casa por $49 más. <a href="limpieza-de-ventanas.html" style="color:var(--brand-600);font-weight:700">Más sobre ventanas</a>'),
          ('Paneles solares: $7 por panel', 'Agua purificada y cepillo suave, sin caminar sobre los paneles. Secan sin manchas y revisamos todo el arreglo. <a href="limpieza-de-paneles-solares.html" style="color:var(--brand-600);font-weight:700">Más sobre paneles</a>'),
          ('Control de palomas: desde $450', 'Nidos y excremento fuera, malla de acero sujeta al marco sin perforar, espantapájaros gratis y 2 años de garantía. <a href="control-de-palomas.html" style="color:var(--brand-600);font-weight:700">Más sobre palomas</a>'),
          ('Mosquiteros: desde $53.99', 'Malla nueva en el momento, en tu casa, con fibra de vidrio gris o malla todo clima que aguanta el sol del desierto. Marcos nuevos por $10 más.'),
          ('Manchas de agua dura: desde $12 por vidrio', 'Las manchas blancas de los aspersores no salen con una limpieza normal. Se tratan vidrio por vidrio y probamos uno gratis primero.'),
          ('Locales y oficinas: desde $149', 'Vidrio del local por dentro y por fuera por $149, antes de abrir, con descuento mensual. Edificios a $10 por vidrio. Estas páginas están en inglés por ahora, pero Tony cotiza en español.')]),
        ('tiles', 'Cómo funciona', 'Tres pasos, sin llamadas de ventas',
         [('1. Toca lo que necesitas', 'Arriba en esta página. Elige los servicios, pon cuántos paneles o mosquiteros tienes, y el total se calcula solo. Sin correo, sin esperar una llamada.'),
          ('2. Mira tu casa en 3D', 'Elige el estilo de tu casa, los pisos y tu calle. El modelo te muestra el problema en tu casa y cómo queda arreglado, con el precio abajo.'),
          ('3. Mándalo como quieras', 'Texto, correo o formulario, ya escrito. El mensaje le llega a Tony en inglés para que lo lea rápido en el techo, pero puedes escribirle en español y te contesta.')]),
        ('text', 'Dónde', 'Las ciudades donde trabajamos cada semana',
         ['Hesperia es la base. Victorville, Apple Valley, Adelanto, Oak Hills, Phelan, Spring Valley Lake y Silverwood están en la ruta cada semana, sin cargo por viaje. Bajamos la cuesta a Fontana, Rancho Cucamonga, Ontario, Rialto y San Bernardino en días agrupados, con los mismos precios.',
          'Escribe tu código postal en la casilla de arriba y sabes en un segundo si llegamos. Si tu casa está en la montaña, en Crestline, Lake Arrowhead, Big Bear o Wrightwood, también vamos, con un mínimo de $149 por trabajo.']),
        ('text', 'Por qué nosotros', 'Lo que hace diferente a Tony\'s',
         ['El precio no cambia el día del trabajo. Lo que ves en la cotización, o lo que Tony te confirma por escrito después de ver la casa, es lo que pagas. No hay cargos que aparezcan cuando ya está la escalera puesta.',
          'El agua es purificada, sin minerales, así que el vidrio y los paneles secan claros sin dejar manchas. Los mosquiteros se quitan y se tallan. Los rieles se limpian. Eso va incluido, no es un extra.',
          'En el control de palomas, la malla se sujeta al marco del panel con clips. Nunca atornillamos ni perforamos tus paneles ni tu techo, así que la garantía de tu sistema solar queda intacta. Y limpiamos y desinfectamos debajo de los paneles para que el olor también se vaya.',
          'Satisfacción garantizada: si algo no queda bien, lo repetimos antes de irnos. Tenemos seguro de responsabilidad civil y mandamos el certificado si lo pides.']),
        ('cta', 'Tu precio, <span class="grad">ahora mismo</span>', 'Arma tu cotización arriba. No pagas nada hasta que el trabajo esté hecho.', 'Ver mi precio'),
    ],
    'faq_title': 'Preguntas frecuentes',
    'faq': [
        ('¿Hablan español?', 'Puedes escribirle a Tony en español por mensaje de texto al 714-559-0300 y te contesta. Esta página y la cotización están en español. El mensaje que se genera para Tony va en inglés para que lo lea rápido cuando está trabajando.'),
        ('¿Cuánto cuesta la limpieza de ventanas?', '$149 por fuera en una casa de un piso y $249 en dos pisos, con mosquiteros, rieles y repisas incluidos. Todas las ventanas por dentro son $49 más en la misma visita. Si reservas en nuestro sitio, la primera visita tiene 10% de descuento.'),
        ('¿Cobran por venir a ver?', 'No. La inspección es gratis y no hay cargo por viaje en el High Desert ni en el Inland Empire. Tony te da el precio por escrito antes de empezar.'),
        ('¿Cómo pago?', 'Cuando el trabajo está hecho y lo revisaste: tarjeta, efectivo o cheque. No se paga nada por adelantado.'),
        ('¿Tienen seguro?', 'Sí. Tenemos seguro de responsabilidad civil y mandamos el certificado cuando lo pides, que es lo que normalmente piden los negocios y las asociaciones de vecinos.'),
    ],
})

PAGES.append({
    'fn': 'control-de-palomas.html', 'lang': 'es',
    'title': 'Control de palomas en paneles solares, desde $450 | Tony\'s',
    'desc': 'Palomas debajo de tus paneles solares: limpieza de nidos y excremento, malla de acero sujeta sin perforar, espantapájaros gratis y 2 años de garantía.',
    'og_image': OG('pigeon-proofing'), 'crumb': 'Control de palomas', 'parent': None, 'alts': [('en', 'pigeon-proofing.html'), ('es', 'control-de-palomas.html'), ('x-default', 'pigeon-proofing.html')],
    'where': 'Hesperia, el High Desert y el Inland Empire', 'area': HD,
    'h1': 'Control de <span class="grad">palomas</span> en paneles solares',
    'tagline': '$450 hasta 12 paneles, con 2 a 3 espantapájaros gratis. Limpieza, malla sujeta al marco sin perforar, lavado de paneles y de techo incluidos.',
    'lede': 'Las palomas buscan sombra, calor y un lugar donde nadie las moleste, y el espacio debajo de un panel solar es exactamente eso. Una pareja hoy es una parvada en primavera. El excremento mancha la teja, tapa las celdas, y el olor a amoniaco entra por las ventilas del ático en las tardes de calor. Esto es lo que hacemos para que se vayan y no regresen.',
    'schema_name': 'Control de palomas en paneles solares', 'service_type': 'Control de palomas en paneles solares', 'price': '450.00',
    'price_desc': 'Control de palomas hasta 12 paneles: limpieza, desinfección, malla rígida de acero sujeta al marco, 2 a 3 espantapájaros, lavado de paneles y de techo.',
    'sections': [
        ('tiles', 'El trabajo', 'Lo que incluye cada trabajo',
         [('Limpieza y desinfección', 'Nidos, huevos, excremento y basura fuera de debajo de cada panel, en bolsas y fuera del techo, no barridos al patio. Luego se desinfecta el área para que el olor se vaya con ellas.'),
          ('Malla de acero, con clips', 'Malla rígida de acero que no se oxida, nunca alambre de gallinero, cortada a la medida y sujeta con clips que se agarran del borde del marco del panel. Nada se perfora ni se atornilla, así que la garantía de tus paneles queda intacta.'),
          ('Espantapájaros gratis', 'Dos o tres espantapájaros reflectantes en las ventilas del techo, con abrazaderas, sin perforar. Su destello evita que las palomas se paren en el techo abierto. Los extra son $50 cada uno.'),
          ('Paneles y techo lavados', 'Lavado de los paneles con agua purificada y lavado suave del techo, los dos incluidos. Por separado serían $7 por panel y desde $599.')]),
        ('text', 'Por qué clips', 'Por qué no atornillamos nunca',
         ['Las cuadrillas baratas atornillan la malla al marco del panel o al techo. Cada hoyo es una entrada de agua y un motivo para que la compañía solar niegue una garantía. Con el viento del High Desert, la malla atornillada se afloja en un par de temporadas y empieza a golpear.',
          'Nuestros clips se agarran del borde interior del marco de aluminio. El viento empuja la malla contra el clip, no lejos de él. Y si algún día un panel necesita servicio, los clips se quitan a mano y se vuelven a poner.']),
        ('text', 'Precio', 'Cuánto cuesta, con la cuenta hecha',
         ['$450 cubre hasta 12 paneles. Cada panel después de 12 es $50 más. Un arreglo de 20 paneles sale en $850, uno de 30 en $1,350. Eso incluye la limpieza, la desinfección, la malla, los espantapájaros, el lavado de paneles y el lavado de techo. El número que ves en la cotización de arriba es el número, confirmado por escrito, y no se le agrega nada el día del trabajo.',
          'Si reservas en nuestro sitio, el día tiene 10% de descuento. La garantía es de 2 años sin palomas, por escrito. Si vuelven a meterse debajo de los paneles en ese tiempo, regresamos.']),
        ('text', 'El olor', 'Lo que nadie te dice',
         ['El excremento seco y los nidos viejos sueltan un olor fuerte a amoniaco que empeora con el calor del verano y entra a la casa por las ventilas del ático. Lavar no basta; el olor vive en las grietas de la teja y en la madera del techo. Por eso desinfectamos el área del nido y por donde escurre, y luego enjuagamos. En una semana de calor se nota la diferencia.']),
        ('cta', 'Cerrado antes de la <span class="grad">próxima cría</span>', 'Pon cuántos paneles tienes arriba. El precio que ves es el precio.', 'Ver mi precio'),
    ],
    'faq_title': 'Preguntas sobre palomas',
    'faq': [
        ('¿Cuánto cuesta el control de palomas?', '$450 hasta 12 paneles y $50 por cada panel adicional, con limpieza, desinfección, malla, 2 a 3 espantapájaros, lavado de paneles y lavado de techo incluidos. Un arreglo de 20 paneles sale en $850.'),
        ('¿Perforan el techo o los paneles?', 'No. La malla se sujeta al borde del marco del panel con clips de acero y los espantapájaros van en las ventilas con abrazaderas. Nada queda con un hoyo.'),
        ('¿Se va el olor?', 'Sí, cuando el material del nido sale y el área se desinfecta. Lavar solo no lo quita. Si después de una semana de calor sigue oliendo, llama y regresamos.'),
        ('¿Y las manchas en la teja?', 'El excremento fresco sale por completo. El que lleva un año o más en teja de concreto deja una sombra que a veces no se va del todo. Te lo decimos antes de empezar.'),
        ('¿Hay garantía?', 'Dos años sin palomas, por escrito. Si se vuelven a meter debajo de los paneles en ese tiempo, regresamos sin costo.'),
    ],
})

PAGES.append({
    'fn': 'limpieza-de-ventanas.html', 'lang': 'es',
    'title': 'Limpieza de ventanas en Hesperia, desde $149 | Tony\'s',
    'desc': 'Limpieza de ventanas en Hesperia, Victorville y Apple Valley: $149 un piso, $249 dos pisos, mosquiteros y rieles incluidos. Por dentro, toda la casa por $49.',
    'og_image': OG('window-cleaning'), 'crumb': 'Limpieza de ventanas', 'parent': None, 'alts': [('en', 'window-cleaning.html'), ('es', 'limpieza-de-ventanas.html'), ('x-default', 'window-cleaning.html')],
    'where': 'Hesperia y todo el High Desert', 'area': HD,
    'h1': 'Limpieza de <span class="grad">ventanas</span> con agua purificada',
    'tagline': '$149 un piso, $249 dos pisos, por fuera, con mosquiteros, rieles y repisas incluidos. Por dentro, todas las ventanas de la casa por $49 más.',
    'lede': 'Aquí arriba las ventanas no se ensucian igual que en la ciudad. El polvo del desierto llega con cada viento y los aspersores dejan minerales que se hornean en el vidrio con el sol. Una limpieza con agua purificada quita las dos cosas y deja el vidrio claro más tiempo, porque no queda nada que atraiga el polvo.',
    'schema_name': 'Limpieza de ventanas', 'service_type': 'Limpieza de ventanas residencial', 'price': '149.00',
    'price_desc': 'Limpieza exterior de ventanas, $149 un piso y $249 dos pisos, mosquiteros, rieles y repisas incluidos.',
    'sections': [
        ('tiles', 'Incluido', 'Lo que trae cada limpieza',
         [('Mosquiteros', 'Se quitan, se tallan y se enjuagan, y vuelven a su lugar. Un mosquitero gris tapa más luz de lo que parece, y la tierra se regresa al vidrio si no se limpia.'),
          ('Rieles y repisas', 'Los rieles se limpian y las repisas se secan. Casi todas las cuadrillas limpian por fuera y dejan el agua sucia en el riel. Nosotros no.'),
          ('Agua purificada', 'Agua sin minerales, así que el vidrio seca claro y sin manchas. Los segundos pisos se limpian desde el suelo con una pértiga, sin escaleras recargadas en tu estuco.')]),
        ('text', 'Por dentro', 'Las ventanas de adentro, por $49',
         ['Por dentro, todas las ventanas de la casa por $49 en la misma visita, no un precio por ventana. Incluye el vidrio de adentro, los marcos y los rieles aspirados y secados, que es lo que hace que las ventanas vuelvan a correr como cuando la casa era nueva. Zapatos cubiertos, telas debajo de cada ventana, y los muebles se mueven y se regresan.']),
        ('text', 'Agua dura', 'Las manchas blancas que no salen',
         ['Si tienes una banda blanca o manchas redondas en los vidrios que dan al pasto, eso es agua dura de los aspersores, minerales pegados al vidrio. No sale con una limpieza normal. Se trata vidrio por vidrio, desde $12 cada uno, y probamos un vidrio gratis primero para que veas el resultado antes de pagar el resto. También te decimos qué aspersor está mojando el vidrio, para que no regrese.']),
        ('text', 'Precio', 'Cuánto cuesta',
         ['$149 un piso, $249 dos pisos, por fuera, con mosquiteros, rieles y repisas. Más de 12 ventanas en un piso o 20 en dos pisos son $39 fijos más. Por dentro, toda la casa, $49. Casas grandes o de lago se cotizan después de verlas, normalmente $499 a $599 por dentro y por fuera, confirmado por escrito.',
          'Si reservas en nuestro sitio, la primera visita tiene 10% de descuento. Con un plan de dos veces al año, cada visita después de la primera tiene 15% de descuento; cada 3 meses, 25%. Tony te manda un mensaje antes de cada visita y puedes moverla o saltarla.']),
        ('cta', 'Vidrio claro <span class="grad">esta semana</span>', 'Elige tu casa arriba y el precio es tu precio.', 'Ver mi precio'),
    ],
    'faq_title': 'Preguntas sobre ventanas',
    'faq': [
        ('¿Cuánto cuesta limpiar las ventanas?', '$149 por fuera en una casa de un piso y $249 en dos pisos, con mosquiteros, rieles y repisas incluidos. Por dentro, todas las ventanas por $49 más en la misma visita.'),
        ('¿Usan escaleras en las casas de dos pisos?', 'Casi nunca. Las ventanas de arriba se limpian desde el suelo con una pértiga y agua purificada, sin escaleras recargadas en el estuco y sin nada que manche.'),
        ('¿Limpian los mosquiteros?', 'Sí, se quitan, se tallan, se enjuagan y vuelven a su lugar. Va incluido en el precio, igual que los rieles y las repisas.'),
        ('¿Salen las manchas de los aspersores?', 'Las manchas de agua dura necesitan un tratamiento aparte, desde $12 por vidrio, solo en los vidrios que lo necesitan. Probamos uno gratis primero para que veas el resultado.'),
        ('¿Cada cuánto conviene limpiarlas?', 'Dos veces al año en la mayoría de las colonias, y cada 3 meses en casas junto al desierto abierto, caminos de tierra o aspersores. Con un plan, esas visitas tienen 15% o 25% de descuento después de la primera.'),
    ],
})

PAGES.append({
    'fn': 'limpieza-de-paneles-solares.html', 'lang': 'es',
    'title': 'Limpieza de paneles solares, $7 por panel | Tony\'s',
    'desc': 'Limpieza de paneles solares en Hesperia, Victorville y Apple Valley a $7 por panel. Agua purificada y cepillo suave, sin pisar los paneles. Secan sin manchas.',
    'og_image': OG('solar-panel-cleaning'), 'crumb': 'Limpieza de paneles solares', 'parent': None, 'alts': [('en', 'solar-panel-cleaning.html'), ('es', 'limpieza-de-paneles-solares.html'), ('x-default', 'solar-panel-cleaning.html')],
    'where': 'Hesperia, el High Desert y el Inland Empire', 'area': HD,
    'h1': 'Limpieza de <span class="grad">paneles solares</span>',
    'tagline': '$7 por panel, con agua purificada y cepillo suave. Nadie camina sobre tus paneles, y revisamos todo el arreglo mientras estamos arriba.',
    'lede': 'Abre tu app solar y compara un día soleado de esta semana con el mismo día un mes después del último lavado. Esa diferencia es lo que el polvo te está quitando cada día. Aquí casi no llueve para enjuagarlo, así que se acumula hasta que alguien lo lava.',
    'schema_name': 'Limpieza de paneles solares', 'service_type': 'Limpieza de paneles solares', 'price': '7.00',
    'price_desc': 'Limpieza de paneles solares con agua purificada y cepillo suave, $7 por panel, secan sin manchas.',
    'sections': [
        ('tiles', 'El método', 'Cómo los limpiamos',
         [('Agua purificada', 'Agua desionizada, sin minerales, así que seca sin dejar la película blanca que tapa la luz. Sin jabón ni químicos que dañen el recubrimiento del panel.'),
          ('Cepillo suave en pértiga', 'Un cepillo de cerdas suaves en una pértiga, trabajado desde la orilla del techo, fila por fila. Sin presión, sin raspadores, y sin pisar los paneles, que puede romper celdas por dentro.'),
          ('Revisión incluida', 'Vidrio roto, cables sueltos y aves debajo de los paneles. Como la mitad de los arreglos que abrimos tienen aves. Te mandamos una foto y una respuesta directa.')]),
        ('text', 'Garantía', 'Seguro para tus paneles y tu garantía',
         ['Los fabricantes piden lo mismo en sus manuales: agua, cepillo suave, nada abrasivo, nada de químicos fuertes ni lavadoras a presión, y no caminar sobre los módulos. Ese es exactamente nuestro método. Lo que anula garantías es el daño, y con agua purificada y un cepillo suave no lo hay. Limpiamos temprano, con los paneles fríos, por la misma razón que dicen los manuales.']),
        ('text', 'Precio y plan', 'Cuánto cuesta y cada cuánto',
         ['$7 por panel, cualquier techo y cualquier tamaño de panel. Veinte paneles son $140. Cuéntalos desde la calle o en tu app solar, aproximado está bien, y lo confirmamos en el techo. Si reservas en nuestro sitio, la primera visita tiene 10% de descuento.',
          'Cada 3 meses es lo que conviene en casas junto al desierto abierto, caminos de tierra o aspersores, y con un plan esas visitas tienen 25% de descuento después de la primera. Dos veces al año en colonias con calles pavimentadas, 15% de descuento. Tony te manda un mensaje antes de cada visita.']),
        ('text', 'Aves', 'Si encontramos palomas',
         ['Si hay palomas debajo de los paneles, te lo decimos con foto. El control de palomas incluye el lavado de paneles gratis, así que lo que pagaste hoy no se pierde. Más detalles en la página de <a href="control-de-palomas.html" style="color:var(--brand-600);font-weight:700">control de palomas</a>.']),
        ('cta', 'Paneles a plena <span class="grad">producción</span>', 'Pon cuántos paneles tienes arriba y mira el lavado en 3D.', 'Ver mi precio'),
    ],
    'faq_title': 'Preguntas sobre paneles solares',
    'faq': [
        ('¿Cuánto cuesta limpiar los paneles solares?', '$7 por panel. Veinte paneles son $140. Si reservas en nuestro sitio, la primera visita tiene 10% de descuento, y en un plan cada 3 meses las visitas siguientes tienen 25% menos.'),
        ('¿Afecta la garantía de mis paneles?', 'No. Agua purificada, cepillo suave, sin químicos, sin presión y sin caminar sobre los módulos es justo lo que piden los fabricantes.'),
        ('¿Caminan sobre los paneles?', 'No. Trabajamos desde la orilla del techo con una pértiga. Pisar un panel puede romper celdas que se ven bien desde abajo.'),
        ('¿Cada cuánto hay que lavarlos?', 'Cada 3 meses junto al desierto abierto, caminos de tierra o aspersores; dos veces al año en colonias con calles pavimentadas; y por lo menos una vez al año en cualquier caso. La lluvia de aquí no alcanza.'),
        ('¿Qué pasa si encuentran palomas?', 'Te mandamos una foto y te decimos qué hay. El control de palomas incluye el lavado de paneles gratis, así que la limpieza de hoy se abona a cerrar el arreglo.'),
    ],
})
