# Page specs, English, part 3: Inland Empire cities, Spring Valley Lake pigeons, and the commercial pages.
S = 'https://twindowclean.com/'
OG = lambda n: S + 'assets/og/' + n + '.jpg'


def city(name, locality, zip_, lat, lon):
    return [{'@type': 'City', 'name': name, 'address': {'@type': 'PostalAddress', 'addressLocality': locality, 'addressRegion': 'CA', 'postalCode': zip_, 'addressCountry': 'US'},
             'geo': {'@type': 'GeoCoordinates', 'latitude': lat, 'longitude': lon}}]


PAGES = []

PAGES.append({
    'fn': 'pigeon-proofing-spring-valley-lake.html',
    'title': 'Pigeon Proofing in Spring Valley Lake | Tony\'s',
    'desc': 'Pigeon proofing solar panels in Spring Valley Lake from $450. Lakefront roofs draw more birds. Cleanout, mesh clipped to the frame, free spinners, warranty.',
    'og_image': OG('spring-valley-lake'), 'crumb': 'Spring Valley Lake', 'parent': ('Pigeon Proofing', S + 'pigeon-proofing.html'),
    'where': 'Serving Spring Valley Lake and the High Desert', 'area': city('Spring Valley Lake', 'Victorville', '92395', '34.4936', '-117.2694'),
    'h1': 'Pigeon Proofing in <span class="grad">Spring Valley Lake</span>', 'tagline': 'From $450 with 2 to 3 spinners free. Water nearby means more birds, and a lakefront array is the first roof on the block they find.',
    'lede': 'Pigeons need water every day, and a lake surrounded by warm tile roofs with solar arrays is the best neighborhood they will ever find. Spring Valley Lake calls run heavier than the tracts around it, and the birds settle in faster because the water is a short flight from the panels.',
    'schema_name': 'Pigeon Proofing in Spring Valley Lake', 'service_type': 'Solar panel pigeon proofing', 'price': '450.00',
    'price_desc': 'Pigeon proofing up to 12 panels with cleanout, rigid mesh clipped to the frame, 2 to 3 free spinners, panel wash and roof wash.',
    'sections': [
        ('text', 'Around the lake', 'Why SVL roofs get found first',
         ['Pigeons roost within a short flight of water, and the lake, the golf course ponds and the greenbelt sprinklers all count. A south facing array on a waterfront home in the middle of that is shade, warmth and a drink, and a pair that finds it will have raised a brood before the droppings show on the tile below.',
          'The flock also moves house to house along the water. When one roof gets closed off, the birds try the next array down the shore, which is why the first home on a stretch to get protected stays clear and the neighbors start asking who did it.']),
        ('tiles', 'What we do', 'Same job, lake details',
         [('Cleanout and sanitizing', 'Nests, droppings and debris out from under every panel and hauled off, the roof deck and tile sanitized so the smell goes too. Waterfront breezes carry that smell onto patios, which is often how it gets noticed here.'),
          ('Low profile mesh', 'Rigid steel mesh clipped to the panel frame lip, sitting tight to the array so it does not show from the street or the water. Nothing drilled into the panels or the roof, so warranties and the roof stay intact.'),
          ('Spinners on the vents', 'Two to three reflective spinners free, held with hose clamps. On a two story with panels facing the lake and the street, one more at $50 covers the second side.')]),
        ('text', 'Price', 'What pigeon proofing costs in Spring Valley Lake',
         ['$450 covers up to 12 panels, $50 for each panel over. The larger waterfront arrays with 24 to 30 panels land between $1,050 and $1,350, with the panel wash and a roof soft wash included. Extra spinners are $50 each. The number in the tool above is the number, confirmed in writing, and nothing gets added on the day.',
          'Book on our website and it is 10% off. No trip fee anywhere in SVL, and no charge to come and look.']),
        ('text', 'Afterward', 'Keeping the array clear',
         ['A year of cleanings can be added: three more panel washes every 3 months at $7 a panel, each one a spinner, clip and mesh check. Near the water that check matters, because the flock is always nearby and testing the edges. Two year pigeon free warranty in writing on every job.']),
        ('photos', 'Our work', 'Arrays we have closed off', 'Our own photos from High Desert roofs.',
         [('assets/photos/hub-pigeon-proofing-01.jpg', 'Rigid mesh clipped along the edge of a solar array'),
          ('assets/photos/victorville-pigeon-02.jpg', 'Pigeon proofed solar array in Victorville'),
          ('assets/photos/apple-valley-pigeon-05.jpg', 'Sealed and cleaned solar array in Apple Valley'),
          ('assets/photos/hesperia-pigeon-05.jpg', 'Pigeon mesh and spinners on a Hesperia roof')]),
        ('cta', 'Closed off before the <span class="grad">next brood</span>', 'Set your panel count above. Pick Lake in the 3D to see a home like yours.', 'Get my price'),
    ],
    'faq_title': 'Spring Valley Lake pigeon questions',
    'faq': [
        ('Why do Spring Valley Lake homes get more pigeons?', 'Water. Pigeons roost within a short flight of it, and the lake, the golf course ponds and the sprinklers keep a flock fed and watered year round. A warm tile roof with a solar array next to all that is exactly what they look for.'),
        ('Will the mesh show from the street or the lake?', 'Barely. The mesh is dark, rigid steel that sits tight against the panel frame, inside the shadow line of the array. From the water it reads as the edge of the panels.'),
        ('What does it cost here?', '$450 for up to 12 panels, $50 a panel after that, with cleanout, mesh, spinners, a panel wash and a roof wash included. Large waterfront arrays run $1,050 to $1,350. Extra spinners $50 each.'),
        ('Do you drill into the roof or panels?', 'No. Mesh is clipped to the lip of the panel frame and spinners are clamped to the roof vents. Nothing gets a hole, so the panel warranty and the roof are left alone.'),
        ('Will they just move to my neighbor?', 'Usually, yes. With your array closed off the flock tries the next roof along the water. That is not your problem anymore, and it is normally when the neighbors call.'),
    ],
})

PAGES.append({
    'fn': 'pigeon-proofing-fontana.html',
    'title': 'Pigeon Proofing Solar Panels in Fontana | Tony\'s',
    'desc': 'Pigeon proofing in Fontana from $450, same price as the High Desert and no trip fee. Cleanout, mesh clipped to the frame, free spinners, panel and roof wash.',
    'og_image': OG('pigeon-proofing'), 'crumb': 'Fontana', 'parent': ('Pigeon Proofing', S + 'pigeon-proofing.html'),
    'where': 'Serving Fontana and the Inland Empire', 'area': city('Fontana', 'Fontana', '92336', '34.0922', '-117.4350'),
    'h1': 'Pigeon Proofing in <span class="grad">Fontana</span>', 'tagline': 'From $450 with 2 to 3 spinners free. We come down the hill, same prices as up here, no trip fee.',
    'lede': 'North Fontana went solar early and in large numbers, and the pigeons followed. The newer tracts from Sierra Lakes across to Hunter\'s Ridge have big south facing arrays on tile roofs, close together, with the Lytle Creek wash and the flood channels a short flight away for water. That is a pigeon\'s whole world in one neighborhood.',
    'schema_name': 'Pigeon Proofing in Fontana', 'service_type': 'Solar panel pigeon proofing', 'price': '450.00',
    'price_desc': 'Pigeon proofing up to 12 panels with cleanout, rigid mesh clipped to the frame, 2 to 3 free spinners, panel wash and roof wash.',
    'sections': [
        ('tiles', 'Neighborhoods', 'Where the Fontana calls come from',
         [('North Fontana', 'Sierra Lakes, Coyote Canyon, Summit Heights and Hunter\'s Ridge. Newer two story tracts with large arrays, and HOAs that care what the roof looks like from the street. Low profile clipped mesh is built for exactly that.'),
          ('Southridge', 'Established single story homes with retrofit arrays, often split across two roof planes. Two roof faces means the second free spinner earns its keep.'),
          ('Jurupa Hills and south of the 10', 'Older tile roofs where the birds have often been under the panels for years. The cleanout is bigger here and the price is the same.')]),
        ('text', 'HOA', 'What the mesh looks like from the street',
         ['Fontana HOAs ask two things: no visible changes to the roof line and nothing that looks like chicken wire. Our mesh is dark, rigid steel that sits inside the shadow line of the panels and is clipped to the frame lip rather than screwed, so there are no fasteners, no brackets and no holes in the roof. From the sidewalk the array looks the way it did the day it was installed, minus the birds.']),
        ('text', 'Price', 'What pigeon proofing costs in Fontana',
         ['Same as the High Desert: $450 covers up to 12 panels, $50 for each panel over, with the cleanout, sanitizing, mesh, 2 to 3 spinners, a purified water panel wash and a roof soft wash included. A 20 panel array is $850, a 28 panel array is $1,250. No trip fee to come down the hill, and no charge to look.',
          'Book on our website and it is 10% off. Two year pigeon free warranty in writing.']),
        ('text', 'Down the hill', 'How scheduling works for the IE',
         ['We come down through the Cajon Pass on days already booked in the Inland Empire, so Fontana jobs are grouped with Rancho Cucamonga, Rialto and Ontario. Send your quote and pick morning or afternoon, and Tony texts back with the soonest day already down there. Solar panel cleaning in Fontana is a separate page if the birds have not found you yet.']),
        ('photos', 'Our work', 'Arrays we have closed off', 'Our own photos, real jobs.',
         [('assets/photos/hub-pigeon-proofing-02.jpg', 'Pigeon mesh running the full edge of a solar array'),
          ('assets/photos/hub-pigeon-proofing-03.jpg', 'Close view of mesh held by frame clips'),
          ('assets/photos/apple-valley-pigeon-01.jpg', 'Two story home with the array sealed'),
          ('assets/photos/oak-hills-pigeon-05.jpg', 'Sealed array on a tile roof')]),
        ('cta', 'Fontana, <span class="grad">same price</span> as up the hill', 'Set your panel count above. No trip fee, firm number.', 'Get my price'),
    ],
    'faq_title': 'Fontana pigeon proofing questions',
    'faq': [
        ('Do you really come to Fontana?', 'Yes. Fontana is one of our regular Inland Empire stops, grouped with Rancho Cucamonga, Rialto and Ontario. No trip fee and the same prices as the High Desert.'),
        ('What does it cost in Fontana?', '$450 for up to 12 panels and $50 for each panel over, with the cleanout, mesh, 2 to 3 spinners, a panel wash and a roof wash included. A 20 panel array is $850.'),
        ('Will my HOA have a problem with the mesh?', 'We have not had one. The mesh is dark steel that sits inside the shadow line of the panels, clipped to the frame with no brackets, screws or roof penetrations. From the street the roof line does not change.'),
        ('How soon can you get here?', 'Usually within the week, on a day we are already down the hill. Send your quote with a morning or afternoon preference and Tony texts back the day.'),
        ('Do you clean the panels too?', 'Yes, a purified water wash of the whole array and a roof soft wash are included with pigeon proofing. On their own those would be $7 a panel and from $599.'),
    ],
})

PAGES.append({
    'fn': 'pigeon-proofing-rancho-cucamonga.html',
    'title': 'Pigeon Proofing in Rancho Cucamonga and Etiwanda | Tony\'s',
    'desc': 'Pigeon proofing solar panels in Rancho Cucamonga, Etiwanda and Alta Loma from $450. Clips that hold in Santa Ana wind, no drilling, HOA friendly, no trip fee.',
    'og_image': OG('pigeon-proofing'), 'crumb': 'Rancho Cucamonga', 'parent': ('Pigeon Proofing', S + 'pigeon-proofing.html'),
    'where': 'Serving Rancho Cucamonga and the Inland Empire', 'area': city('Rancho Cucamonga', 'Rancho Cucamonga', '91739', '34.1064', '-117.5931'),
    'h1': 'Pigeon Proofing in <span class="grad">Rancho Cucamonga</span>', 'tagline': 'From $450 with 2 to 3 spinners free. Built for Etiwanda wind and Alta Loma HOAs: clipped, never screwed.',
    'lede': 'Rancho Cucamonga sits right where the Cajon Pass empties out, so when the Santa Anas blow, Etiwanda and Day Creek get the full force of it. That wind is why pigeon mesh screwed to the frame fails here within a couple of seasons, and why every array we proof in this city is clipped instead.',
    'schema_name': 'Pigeon Proofing in Rancho Cucamonga', 'service_type': 'Solar panel pigeon proofing', 'price': '450.00',
    'price_desc': 'Pigeon proofing up to 12 panels with cleanout, rigid mesh clipped to the frame, 2 to 3 free spinners, panel wash and roof wash.',
    'sections': [
        ('tiles', 'Neighborhoods', 'Where we work in Rancho',
         [('Etiwanda and Day Creek', 'The windiest streets in the Inland Empire and some of the biggest arrays. Clips grip the frame lip so the wind pushes the mesh into them, not away. Screwed mesh here rattles loose and starts flapping.'),
          ('Alta Loma', 'Larger lots up against the foothills, mature trees, and roosting pressure from the wash and the flood control basins. Two roof faces on many homes, so both free spinners get used.'),
          ('Victoria and Terra Vista', 'Master planned tracts with strict architectural rules. Low profile dark mesh with no visible fasteners keeps the roof line unchanged from the street.')]),
        ('text', 'Wind', 'Why clips matter more here',
         ['Santa Ana wind loads a sheet of mesh like a sail. A screw through the frame holds until the mesh has flexed against it a few thousand times, then the hole elongates and the mesh works loose, usually starting at a corner. A clip pins the mesh against the frame lip across its whole width, and the harder the wind pushes, the tighter it sits. Nothing is drilled into the panel or the roof, so nothing is left behind if a panel ever needs service.']),
        ('text', 'HOA', 'Getting it past the architectural committee',
         ['Most Rancho HOAs do not require approval for pigeon mesh because it is not visible from the street and nothing on the roof changes. If yours asks, we provide a one page description: rigid steel mesh, dark finish, clipped to the module frame, no penetrations, removable. That has been enough every time.']),
        ('text', 'Price', 'What pigeon proofing costs in Rancho Cucamonga',
         ['$450 covers up to 12 panels, $50 for each panel over, with the cleanout, sanitizing, mesh, 2 to 3 free spinners, a purified water panel wash and a roof soft wash. Same price as the High Desert, no trip fee to come down the hill. Book on our website and it is 10% off. Two year pigeon free warranty in writing.',
          'Rancho jobs are grouped with Fontana, Upland and Ontario, so the soonest day is usually within the week.']),
        ('photos', 'Our work', 'Mesh that holds in the wind', 'Our own photos, real jobs.',
         [('assets/photos/hub-pigeon-proofing-03.jpg', 'Close view of pigeon mesh held by frame clips'),
          ('assets/photos/hub-pigeon-proofing-01.jpg', 'Rigid mesh clipped along the edge of a solar array'),
          ('assets/photos/hesperia-pigeon-04.jpg', 'Pigeon proofed array on a tile roof'),
          ('assets/photos/victorville-pigeon-01.jpg', 'Sealed solar array after cleanout')]),
        ('cta', 'Clipped for <span class="grad">Etiwanda wind</span>', 'Set your panel count above. Same price as up the hill, no trip fee.', 'Get my price'),
    ],
    'faq_title': 'Rancho Cucamonga pigeon proofing questions',
    'faq': [
        ('Does the mesh hold in Santa Ana winds?', 'Yes, because it is clipped, not screwed. The clip pins the mesh against the frame lip across its width, so wind pushes it tighter. Screwed mesh is what works loose in Etiwanda and starts flapping at a corner.'),
        ('Do I need HOA approval?', 'Usually not, because nothing visible changes and there are no penetrations. If your HOA asks, we provide a one page description of the material and the clip system, which has been accepted every time.'),
        ('What does it cost?', '$450 for up to 12 panels and $50 a panel after that, including the cleanout, mesh, 2 to 3 spinners, a panel wash and a roof wash. No trip fee for Rancho Cucamonga.'),
        ('Do you cover Etiwanda and Alta Loma?', 'Yes, all of Rancho Cucamonga including Etiwanda, Alta Loma, Day Creek, Victoria and Terra Vista, grouped with our Fontana, Upland and Ontario days.'),
        ('What about the panels themselves?', 'A purified water wash of the whole array is included, and every panel is checked for cracks and loose wiring while we are up there. Nothing is drilled and nobody walks on the modules.'),
    ],
})

PAGES.append({
    'fn': 'solar-panel-cleaning-fontana.html',
    'title': 'Solar Panel Cleaning in Fontana, $7 a Panel | Tony\'s',
    'desc': 'Solar panel cleaning in Fontana for $7 a panel with purified water and a soft brush. Freeway dust, Santa Ana grit and droppings off, dried spot free.',
    'og_image': OG('solar-panel-cleaning'), 'crumb': 'Fontana', 'parent': ('Solar Panel Cleaning', S + 'solar-panel-cleaning.html'),
    'where': 'Serving Fontana and the Inland Empire', 'area': city('Fontana', 'Fontana', '92336', '34.0922', '-117.4350'),
    'h1': 'Solar Panel Cleaning in <span class="grad">Fontana</span>', 'tagline': '$7 a panel, purified water and a soft brush, dried spot free. Nobody walks on your panels and there is no trip fee.',
    'lede': 'Fontana panels collect a specific kind of dirt: fine black dust off the 10, the 15 and the 210, grit the Santa Anas bring down the Cajon, and whatever the warehouse traffic on Sierra and Cherry kicks up. It does not rinse off in the rain, it smears. Purified water and a soft brush lift it without leaving a spot.',
    'schema_name': 'Solar Panel Cleaning in Fontana', 'service_type': 'Solar panel cleaning', 'price': '7.00',
    'price_desc': 'Solar panel cleaning with purified water and a soft brush, $7 a panel, dried spot free.',
    'sections': [
        ('tiles', 'What is on Fontana panels', 'Three layers, one wash',
         [('Freeway film', 'Diesel and tire dust settles as a dark film that rain smears instead of clearing. It cuts output more than the pale desert dust up the hill because it is darker.'),
          ('Santa Ana grit', 'Wind events drop sand and pollen across North Fontana in a day. Left on a hot panel with morning dew it cements at the bottom edge of each module.'),
          ('Birds', 'About half the arrays we open have birds under them. Droppings on a single cell pull a whole panel down, and the nesting means the pigeon page, not this one.')]),
        ('text', 'The method', 'How the panels get cleaned',
         ['Deionized water fed through a soft brush on a pole, worked row by row from the roof edge, then rinsed with the same water so nothing is left to dry into spots. No soap, no scrapers, no pressure washer, and nobody stands on the modules. It is the method every panel maker\'s manual asks for, so your warranty is not in question.',
          'A Fontana customer put it simply in her Google review: the panels are so clean and look awesome. That is the standard.']),
        ('text', 'Price and schedule', 'What it costs in Fontana',
         ['$7 a panel, any pitch, any panel size. Twenty panels is $140. Count them from the street or your solar app and we confirm on the roof. Every 3 months on a plan is 25% off each visit after the first, which is the right schedule for homes near the freeways and the truck routes. No trip fee to come down the hill. Book on our website and the first visit is 10% off.',
          'If we find birds under the array, pigeon proofing in Fontana includes this wash free, so nothing you paid today is lost.']),
        ('photos', 'Our work', 'Panels washed with purified water', 'Our own photos, real jobs.',
         [('assets/photos/hub-solar-02.jpg', 'Solar array being washed with a water fed pole'),
          ('assets/photos/hub-solar-03.jpg', 'Clean solar panels after a purified water rinse'),
          ('assets/photos/victorville-solar-02.jpg', 'Clean array on a two story home'),
          ('assets/photos/adelanto-solar-01.jpg', 'Panels dried spot free after cleaning')]),
        ('cta', 'Full output, <span class="grad">no trip fee</span>', 'Set your panel count above and watch the wash in 3D.', 'Get my price'),
    ],
    'faq_title': 'Fontana solar cleaning questions',
    'faq': [
        ('How much is solar panel cleaning in Fontana?', '$7 a panel with purified water and a soft brush. Twenty panels is $140. No trip fee, and 10% off the first visit when you book on our website.'),
        ('How often do Fontana panels need cleaning?', 'Every 3 months for homes near the freeways, rail lines or warehouse routes, twice a year for quieter streets. The freeway film is dark and rain smears it rather than clearing it.'),
        ('Is it safe for the panels and the warranty?', 'Yes. Purified water, a soft brush, no chemicals, no pressure and nobody walking on the modules is exactly what the manufacturer manuals ask for.'),
        ('What if you find birds under the panels?', 'You get a photo and a straight answer. Pigeon proofing in Fontana includes the panel wash free, so the cleaning you paid for is credited toward closing the array off.'),
        ('Which parts of Fontana do you cover?', 'All of it: North Fontana, Southridge, Jurupa Hills and everything between, grouped with our Rancho Cucamonga and Rialto days.'),
    ],
})

PAGES.append({
    'fn': 'storefront-window-cleaning.html',
    'title': 'Storefront Window Cleaning, $149 Inside and Out | Tony\'s',
    'desc': 'Storefront window cleaning for $149 flat, 8 to 10 panes inside and out, doors included. Monthly 15% off, every 2 weeks 25% off. Build yours in 3D.',
    'og_image': OG('commercial-window-cleaning'), 'crumb': 'Storefronts', 'parent': ('Commercial Window Cleaning', S + 'commercial-window-cleaning.html'),
    'where': 'Serving storefronts across the High Desert',
    'h1': 'Storefront <span class="grad">Window Cleaning</span>', 'tagline': '$149 flat for 8 to 10 panes inside and out, doors included. Before you open, on a schedule, one invoice a month.',
    'lede': 'Customers judge a shop by its glass before they read the sign. Out here a couple of windy weeks is enough to make a clean store look closed. A flat price, a set schedule and a crew that is done before your first customer is the whole idea, and the 3D above lets you build your own storefront and see the number.',
    'schema_name': 'Storefront Window Cleaning', 'service_type': 'Commercial window cleaning', 'price': '149.00',
    'price_desc': 'Storefront glass inside and out, 8 to 10 panes with doors, $149 flat per visit.',
    'sections': [
        ('tiles', 'The price', 'Flat, and it gets cheaper on a schedule',
         [('$149 one time', 'Eight to ten panes inside and out, glass doors counted as panes, frames wiped, handprints gone. Past ten panes it is a flat $50 more for the rest, however many.'),
          ('Monthly 15% off, every 2 weeks 25% off', '$126.65 or $111.75 a visit month to month. Every 2 weeks is what restaurants and salons with a lot of hands on the door end up choosing.'),
          ('Agreements 20% and 40% off', 'A quarterly agreement takes 20% off every visit, a yearly agreement 40%, at $89.40 a visit. The better discount applies, never both, and the price is locked for the term.')]),
        ('text', 'Extras', 'What else the visit can include',
         ['Interior partitions and mirrors, $50 flat: the glass between the register and the seating, mirrored walls in a salon, display cases. Rotating vinyl stickers, $10 each: when your hours or promos change, the old sticker comes off clean and the new one goes up straight while we are there. You supply the stickers, we handle the glass.',
          'Hard water on the outside glass from the parking lot sprinklers is checked on every visit and removed pane by pane when it is there.']),
        ('text', 'How it runs', 'Early, quiet, invoiced once',
         ['Storefronts are done before opening or after close, whichever your center allows. Purified water and a squeegee inside and out, doors and frames wiped, and the sidewalk under the glass rinsed. Same day every cycle, one invoice at the end of the month, and a text the day before so there are no surprises.',
          'Property managers with several sites get one schedule and one invoice across all of them, and a certificate of general liability insurance on file before we start.']),
        ('text', 'Build it', 'See your own storefront and its price',
         ['The 3D above has four storefront styles, your name on the sign, and a builder that lets you add, move and resize panes and doors and drop stickers on the glass. Every change updates the price below it. It is the same tool Tony uses on a walk up, so the number you see is the number you get.']),
        ('cta', 'Glass that <span class="grad">opens the door</span>', 'Set your panes and schedule above. The price is flat and firm.', 'Get my price'),
    ],
    'faq_title': 'Storefront window cleaning questions',
    'faq': [
        ('How much does storefront window cleaning cost?', '$149 flat for 8 to 10 panes inside and out, doors included. Past 10 panes is a flat $50 more. Monthly is 15% off every visit, every 2 weeks 25% off, a quarterly agreement 20% off and a yearly agreement 40% off.'),
        ('Do you come before we open?', 'Yes. Before opening or after close, whichever your center allows, and the same day every cycle so your staff know when to expect us.'),
        ('Can you change our window stickers?', 'Yes. Rotating vinyl stickers are $10 each: old one off clean, new one up straight, while we are there. You supply the stickers.'),
        ('How is it billed?', 'One invoice at the end of the month, card, check or transfer. Several locations go on one schedule and one invoice.'),
        ('Are you insured?', 'Yes. General liability insurance is in place and we send a certificate on request, which most centers and property managers ask for before the first visit.'),
    ],
})

PAGES.append({
    'fn': 'office-window-cleaning.html',
    'title': 'Office Building Window Cleaning, $10 a Pane | Tony\'s',
    'desc': 'Office and commercial building window cleaning at $10 a pane inside and out, $10 more a pane per story up. Hard water checked, tint left alone, one invoice.',
    'og_image': OG('commercial-window-cleaning'), 'crumb': 'Office Buildings', 'parent': ('Commercial Window Cleaning', S + 'commercial-window-cleaning.html'),
    'where': 'Serving offices across the High Desert and Inland Empire',
    'h1': 'Office Building <span class="grad">Window Cleaning</span>', 'tagline': '$10 a pane inside and out on the ground floor, $10 more a pane for each story up. Free walkthrough, firm price in writing, worked after hours.',
    'lede': 'Office glass is priced by the pane and by the story, because the second floor takes a pole or a lift and the third takes more of both. The walkthrough is free, the count is agreed before anything starts, and the number in writing is the number on the invoice.',
    'schema_name': 'Office Building Window Cleaning', 'service_type': 'Commercial window cleaning', 'price': '10.00',
    'price_desc': 'Office building window cleaning, $10 a pane inside and out on the ground floor, $10 more a pane for each story up.',
    'sections': [
        ('tiles', 'The math', 'Three buildings, priced',
         [('Single story, 40 panes: $400', '$10 a pane inside and out. A dental office or a small professional building with a glass entry lands here.'),
          ('Two story, 80 panes: $1,200', '40 panes on the ground floor at $10 and 40 on the second at $20. Two story medical and professional buildings along Hesperia Road and Bear Valley Road are this shape.'),
          ('Three story, 120 panes: $2,400', '$10, $20 and $30 a pane by story. Priced after a walkthrough because the third story decides the equipment.')]),
        ('text', 'What is checked', 'Two things we look for on every pane',
         ['Hard water staining, which shows up on the ground floor wherever landscape sprinklers reach the glass. It is noted on the walkthrough and removed pane by pane when you want it gone, priced separately and agreed first. Existing window tint, which is on most office glass out here. Tinted panes get purified water and a soft squeegee, never a blade or an abrasive pad, so the film stays put.']),
        ('text', 'How it runs', 'Quiet, after hours, one invoice',
         ['Exterior glass is done with purified water on a pole from the ground where the building allows it, which means no lift on the sidewalk during business hours. Interior glass is done after hours or early, with tenants told the day before. Frames and sills wiped, entry doors and handprints last, and the walkway rinsed.',
          'One invoice a month across the whole building or all your sites, a text before every visit, and a certificate of general liability insurance on file before the first one.']),
        ('text', 'Schedule', 'How often office glass needs it',
         ['Monthly for entries and ground floor glass that customers touch, quarterly for the upper stories, is the usual split, and the price by pane makes that easy to set up. Set the building size, stories and pane count in the tool above for a starting number, then the walkthrough confirms it in writing.']),
        ('cta', 'Free walkthrough, <span class="grad">firm price</span>', 'Set your building above for a starting number. Tony confirms it on site.', 'Get my price'),
    ],
    'faq_title': 'Office window cleaning questions',
    'faq': [
        ('How much is office window cleaning?', '$10 a pane inside and out on the ground floor and $10 more a pane for each story up, so $20 on the second story and $30 on the third. A two story building with 80 panes is $1,200. The walkthrough is free and the price is confirmed in writing.'),
        ('Do you work around business hours?', 'Yes. Exterior glass is done from the ground with a pole so there is no lift on the sidewalk, and interior glass is done after hours or early with tenants told the day before.'),
        ('Will you damage the window tint?', 'No. Tinted glass gets purified water and a soft squeegee only, never a blade or an abrasive. We note the tinted panes on the walkthrough.'),
        ('Can you remove the hard water spots on the ground floor?', 'Yes, pane by pane, priced separately and agreed before we start. It is noted on the walkthrough so there are no surprises.'),
        ('Are you insured and can you send a certificate?', 'Yes. General liability insurance is in place and we send a certificate before the first visit, which most property managers require.'),
    ],
})

PAGES.append({
    'fn': 'medical-office-window-cleaning.html',
    'title': 'Medical Office Window Cleaning, High Desert | Tony\'s',
    'desc': 'Window cleaning for clinics, dental and medical offices in Apple Valley, Victorville and Hesperia: partitions and sneeze guards, quiet hours, no odors.',
    'og_image': OG('commercial-window-cleaning'), 'crumb': 'Medical Offices', 'parent': ('Commercial Window Cleaning', S + 'commercial-window-cleaning.html'),
    'where': 'Serving clinics across the High Desert',
    'h1': 'Medical Office <span class="grad">Window Cleaning</span>', 'tagline': 'Waiting room glass, reception partitions and sneeze guards, done in quiet hours with purified water and no odors. Priced by the pane.',
    'lede': 'A clinic has more glass inside than out: the reception partition, the sneeze guards at check in, the sidelights on every exam room door, the pharmacy window. It also has patients who notice fingerprints and staff who cannot have a crew in the way at 9 a.m. The work is scheduled around both.',
    'schema_name': 'Medical Office Window Cleaning', 'service_type': 'Commercial window cleaning', 'price': '10.00',
    'price_desc': 'Medical and dental office window cleaning, $10 a pane inside and out, interior partitions and sneeze guards included in the count.',
    'sections': [
        ('tiles', 'Where', 'The medical corridors we work',
         [('Apple Valley', 'The offices around St. Mary Medical Center and along Highway 18 and Apple Valley Road, from single suites to two story professional buildings.'),
          ('Victorville', 'The clinics near Desert Valley Hospital and along Hesperia Road, and the dental and urgent care suites in the retail centers off Bear Valley Road.'),
          ('Hesperia', 'Main Street and Bear Valley Road offices, which are home base for us, so early or late slots are easy to hold.')]),
        ('text', 'What is different', 'How a clinic visit is run',
         ['Quiet hours only: before the first patient or after the last, agreed with your office manager. Purified water and a squeegee, no ammonia and no scented cleaners, so the waiting room does not smell of anything when you open. Partitions and sneeze guards are wiped on both sides and the edges dried so there is no streak at eye level from a chair.',
          'Exam room sidelights and interior doors are done with the door open and closed again behind us. Nothing is moved that we did not ask about first, and every crew member is the same person you met on the walkthrough.']),
        ('text', 'Price', 'What it costs',
         ['$10 a pane inside and out for the exterior glass, with interior partitions and sneeze guards counted as panes at the same rate. A single story clinic with 30 exterior panes and 12 interior pieces is $420. Two story buildings add $10 a pane on the upper floor. The walkthrough is free and the price is confirmed in writing before the first visit.',
          'Most clinics run monthly for the entry and interior glass and quarterly for the rest. One invoice at month end and a certificate of general liability insurance on file.']),
        ('cta', 'Clear glass at <span class="grad">check in</span>', 'Set your building above for a starting number. The walkthrough makes it firm.', 'Get my price'),
    ],
    'faq_title': 'Medical office window questions',
    'faq': [
        ('Can you clean while we are open?', 'We schedule before the first patient or after the last, whichever your office manager prefers. Exterior glass can be done from outside during the day without anyone coming in.'),
        ('Do you clean the sneeze guards and partitions?', 'Yes, both sides, edges dried, counted as panes at $10 each alongside the windows. That is usually the glass patients look through the most.'),
        ('What do you clean with?', 'Purified water and a squeegee. No ammonia, no scented products, nothing that leaves an odor in a waiting room or a residue on the glass.'),
        ('How much does it cost?', '$10 a pane inside and out, interior partitions counted the same way, $10 more a pane on an upper story. A free walkthrough sets the count and the price is confirmed in writing.'),
        ('Do you have insurance we can keep on file?', 'Yes. General liability insurance is in place and a certificate is sent before the first visit.'),
    ],
})
